begin;
do $$declare a uuid; b uuid; adminid uuid; sid uuid; ts timestamptz; archived jsonb; denied boolean; n integer;
begin
 select id into a from public.profiles where role<>'admin' limit 1;
 select id into b from public.profiles where role<>'admin' and id<>a limit 1;
 select id into adminid from public.profiles where role='admin' limit 1;
 if a is null or b is null or adminid is null then raise exception 'test accounts missing';end if;
 insert into public.customer_subscriptions(customer_id,product_id,plan,starts_at,expires_at) values(a,'38ba2004-0021-4717-b06f-dc21493b83b5','demo',now()-interval '1 minute',now()+interval '1 day');
 perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 insert into public.builder_sites(owner_id,name,slug,draft) values(a,'Archive test','archive-'||substr(gen_random_uuid()::text,1,12),'{"pages":[]}') returning id,updated_at into sid,ts;
 insert into public.builder_customers(site_id,full_name) values(sid,'Private archive history');
 perform public.publish_builder_site(sid);
 denied=false;begin perform public.admin_archive_builder_site(sid,false,ts);exception when insufficient_privilege then denied=true;end;
 if not denied then raise exception 'customer archive allowed';end if;
 perform set_config('request.jwt.claim.sub',b::text,true);
 if exists(select 1 from public.builder_sites where id=sid) then raise exception 'cross tenant leak';end if;
 perform set_config('request.jwt.claim.sub',adminid::text,true);
 if not exists(select 1 from public.builder_sites where id=sid) then raise exception 'admin cannot manage customer site';end if;
 update public.builder_sites set name='Edited by admin' where id=sid;get diagnostics n=row_count;
 if n<>1 then raise exception 'admin edit denied';end if;
 denied=false;begin perform public.admin_archive_builder_site(sid,false,ts-interval '1 second');exception when others then denied=true;end;
 if not denied then raise exception 'stale archive accepted';end if;
 archived=public.admin_archive_builder_site(sid,false,ts);
 if archived->>'deleted_at' is null then raise exception 'archive failed';end if;
 if exists(select 1 from public.builder_publications where site_id=sid and is_live) then raise exception 'archive remains published';end if;
 if not exists(select 1 from public.builder_customers where site_id=sid) or not exists(select 1 from public.builder_versions where site_id=sid) then raise exception 'history lost';end if;
 denied=false;begin perform public.publish_builder_site(sid);exception when others then denied=true;end;
 if not denied then raise exception 'archived republish allowed';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 if exists(select 1 from public.builder_sites where id=sid) or exists(select 1 from public.builder_customers where site_id=sid) then raise exception 'archived owner access';end if;
 update public.builder_sites set name='Owner archive edit' where id=sid;get diagnostics n=row_count;
 if n<>0 then raise exception 'archived owner edit';end if;
 denied=false;begin insert into public.builder_customers(site_id,full_name) values(sid,'Forbidden');exception when insufficient_privilege then denied=true;end;
 if not denied then raise exception 'archived CRM insert';end if;
 perform set_config('request.jwt.claim.sub',adminid::text,true);
 perform public.admin_archive_builder_site(sid,true,(archived->>'updated_at')::timestamptz);
 if exists(select 1 from public.builder_publications where site_id=sid and is_live) then raise exception 'restore auto publishes';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 if not exists(select 1 from public.builder_sites where id=sid) or not exists(select 1 from public.builder_customers where site_id=sid) then raise exception 'restore owner history';end if;
 perform public.publish_builder_site(sid);
 execute 'reset role';perform set_config('request.jwt.claim.sub','',true);execute 'set local role anon';
 denied=false;begin perform public.admin_archive_builder_site(sid,false,ts);exception when insufficient_privilege then denied=true;end;
 if not denied then raise exception 'anonymous archive grant';end if;
 execute 'reset role';
end $$;
select 'PASS: admin edit, owner isolation, admin-only archive, stale writes, publication withdrawal, archived writes blocked, history preserved, safe restore' as result;
rollback;
