begin;
do $$ declare a uuid;b uuid;sid uuid;pid uuid;vid uuid;oid uuid;key1 uuid=gen_random_uuid();key2 uuid=gen_random_uuid();receipt jsonb;denied boolean;n integer;sl text='commerce-test-'||substr(gen_random_uuid()::text,1,8);customer jsonb='{"full_name":"مشتری آزمایشی","phone":"09120000001","province":"فارس","city":"شیراز","address":"نشانی آزمایشی فروشگاه","postal_code":"1234567890"}';begin
 select id into a from public.profiles where role<>'admin' order by created_at limit 1;
 select id into b from public.profiles where role<>'admin' and id<>a order by created_at limit 1;
 if a is null or b is null then raise exception 'two existing customers required';end if;
 insert into public.customer_subscriptions(customer_id,product_id,plan,starts_at,expires_at) values(a,'38ba2004-0021-4717-b06f-dc21493b83b5','demo',now()-interval '1 minute',now()+interval '1 day'),(b,'38ba2004-0021-4717-b06f-dc21493b83b5','demo',now()-interval '1 minute',now()+interval '1 day');
 perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 insert into public.builder_sites(owner_id,name,slug,draft) values(a,'آزمون فروشگاه',sl,'{"pages":[{"id":"home","slug":"","title":"خانه","blocks":[]}]}') returning id into sid;
 pid=public.save_builder_product(sid,null,'{"title":"محصول آزمایشی","slug":"test-product","kind":"simple","status":"published"}','[{"label":"پیش‌فرض","sku":"TEST-1","price":100,"stock":5,"manage_stock":true}]');
 select id into vid from public.builder_variants where product_id=pid;
 insert into public.builder_shop_settings(site_id,accepting_orders,shipping_fee,tax_percent) values(sid,true,50,10);
 insert into public.builder_coupons(site_id,code,kind,amount,usage_limit) values(sid,'TEST20','percent',20,1);
 perform public.publish_builder_site(sid);
 perform set_config('request.jwt.claim.sub',b::text,true);
 if exists(select 1 from public.builder_orders where site_id=sid) then raise exception 'cross order read';end if;
 denied=false;begin perform public.save_builder_product(sid,pid,'{}','[]');exception when others then denied=true;end;if not denied then raise exception 'cross catalog write';end if;
 update public.builder_shop_settings set accepting_orders=false where site_id=sid;get diagnostics n=row_count;if n<>0 then raise exception 'cross settings write';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub','',true);execute 'set local role anon';
 if not exists(select 1 from public.builder_products where id=pid) then raise exception 'public product missing';end if;
 denied=false;begin perform count(*) from public.builder_orders;exception when insufficient_privilege then denied=true;end;if not denied then raise exception 'anonymous order grant';end if;
 receipt=public.checkout_builder_store(sl,key1,customer,jsonb_build_array(jsonb_build_object('variant_id',vid,'quantity',2,'price',1)),'TEST20','cod');
 if (receipt->>'total')::bigint<>226 then raise exception 'incorrect server price: %',receipt;end if;
 if public.checkout_builder_store(sl,key1,customer,'[]','','cod')<>receipt then raise exception 'idempotency failed';end if;
 if (public.get_builder_receipt(sl,key1)->>'total')::bigint<>226 then raise exception 'receipt missing';end if;
 if public.get_builder_receipt(sl,gen_random_uuid()) is not null then raise exception 'receipt leaked';end if;
 denied=false;begin perform public.checkout_builder_store(sl,key2,jsonb_set(customer,'{phone}','"09120000002"'),jsonb_build_array(jsonb_build_object('variant_id',vid,'quantity',1)),'TEST20','cod');exception when others then if sqlerrm<>'coupon_invalid' then raise;end if;denied=true;end;if not denied then raise exception 'coupon limit bypass';end if;
 denied=false;begin perform public.checkout_builder_store(sl,key2,jsonb_set(customer,'{phone}','"09120000002"'),jsonb_build_array(jsonb_build_object('variant_id',vid,'quantity',4)),'','cod');exception when others then if sqlerrm<>'stock_unavailable' then raise;end if;denied=true;end;if not denied then raise exception 'oversell permitted';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 if (select stock from public.builder_variants where id=vid)<>3 then raise exception 'stock deduction failed';end if;
 denied=false;begin perform public.save_builder_product(sid,pid,'{"title":"محصول آزمایشی","slug":"test-product","kind":"simple","status":"published"}',jsonb_build_array(jsonb_build_object('id',vid,'label','پیش‌فرض','sku','TEST-1','price',100,'stock',5,'expected_stock',5,'manage_stock',true)),(select updated_at from public.builder_products where id=pid));exception when others then if sqlerrm<>'stock_changed' then raise;end if;denied=true;end;if not denied then raise exception 'stale inventory overwrite';end if;
 select id into oid from public.builder_orders where checkout_key=key1;
 if (select count(*) from public.builder_customers where site_id=sid)<>1 then raise exception 'customer missing';end if;
 perform set_config('request.jwt.claim.sub',b::text,true);
 denied=false;begin perform public.update_builder_order(oid,'cancelled','unpaid');exception when others then denied=true;end;if not denied then raise exception 'cross order update';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform public.update_builder_order(oid,'cancelled','unpaid');perform public.update_builder_order(oid,'cancelled','unpaid');
 if (select stock from public.builder_variants where id=vid)<>5 then raise exception 'restock not exactly once';end if;
 if (select used_count from public.builder_coupons where site_id=sid)<>0 then raise exception 'coupon limit not restored';end if;
 perform public.save_builder_product(sid,pid,'{"title":"ویرایش محصول آزمایشی","slug":"test-product","kind":"simple","status":"published"}',jsonb_build_array(jsonb_build_object('id',vid,'label','پیش‌فرض','sku','TEST-1','price',120,'stock',5,'expected_stock',5,'manage_stock',true)),(select updated_at from public.builder_products where id=pid));
 if (select price from public.builder_variants where id=vid)<>120 then raise exception 'product update failed';end if;
 update public.builder_products set status='draft' where id=pid;
 execute 'reset role';perform set_config('request.jwt.claim.sub','',true);execute 'set local role anon';
 if exists(select 1 from public.builder_products where id=pid) or exists(select 1 from public.builder_variants where id=vid) then raise exception 'draft product leaked';end if;
 denied=false;begin perform public.checkout_builder_store(sl,key2,jsonb_set(customer,'{phone}','"09120000002"'),jsonb_build_array(jsonb_build_object('variant_id',vid,'quantity',1)),'','cod');exception when others then if sqlerrm<>'product_unavailable' then raise;end if;denied=true;end;if not denied then raise exception 'draft purchasable';end if;
 execute 'reset role';
 update public.customer_subscriptions set expires_at=now()-interval '1 second' where customer_id=a and product_id='38ba2004-0021-4717-b06f-dc21493b83b5';
 execute 'set local role anon';denied=false;begin perform public.checkout_builder_store(sl,key2,jsonb_set(customer,'{phone}','"09120000002"'),jsonb_build_array(jsonb_build_object('variant_id',vid,'quantity',1)),'','cod');exception when others then if sqlerrm<>'store_unavailable' then raise;end if;denied=true;end;if not denied then raise exception 'expired store checkout';end if;execute 'reset role';
end $$;
select 'PASS: ownership, guest catalog, private orders, server prices, idempotency, stock, cancellation, coupons, draft visibility' as result;
rollback;
