const ts=require('typescript'),fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'../..');
function load(file,mocks={}){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{fileName:'test.tsx',compilerOptions:{esModuleInterop:true,target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,require:n=>mocks[n]||require(n),React:require('react'),globalThis:{crypto:require('crypto').webcrypto},console});return module.exports}
const design=load('lib/builder-design.js');const site=load('lib/site-builder.js',{'./builder-design':design});
const old={template:'studio',color:'#ff642d',pages:[{id:'home',slug:'',title:'خانه',blocks:[{id:'a',type:'text',title:'متن قدیمی',text:'محتوای محفوظ',items:[]}]}]};
const normalized=site.normalizeDocument(old);assert.equal(normalized.pages[0].columns,1);assert.equal(normalized.pages[0].gap,0);assert.equal(normalized.pages[0].blocks[0].text,'محتوای محفوظ');assert.deepEqual(JSON.parse(JSON.stringify(normalized.pages[0].blocks[0].style)),{});
const custom={...old,pages:[{...old.pages[0],columns:3,gap:16,blocks:[{...old.pages[0].blocks[0],style:{paddingTop:80,span:2,background:'#ffffff',titleSize:42},mobileStyle:{titleSize:24,paddingTop:20}}]}]};const result=site.normalizeDocument(JSON.parse(JSON.stringify(site.normalizeDocument(custom))));assert.equal(result.pages[0].columns,3);assert.equal(result.pages[0].blocks[0].mobileStyle.titleSize,24);assert.equal(result.pages[0].blocks[0].style.span,2);
const bounded=design.normalizeDesign({paddingTop:99999,titleSize:-10,background:'url(javascript:alert(1))',textColor:'#fff',position:'fixed',span:9,hiddenDesktop:true});assert.equal(bounded.paddingTop,240);assert.equal(bounded.titleSize,16);assert.equal(bounded.span,4);assert.equal(bounded.hiddenDesktop,true);assert.equal(bounded.background,undefined);assert.equal(bounded.position,undefined);
const blocks=[{id:'a'},{id:'b'},{id:'c'}];assert.equal(design.reorderBlock(blocks,'c','a').map(b=>b.id).join(','),'c,a,b');assert.equal(blocks.map(b=>b.id).join(','),'a,b,c');assert.equal(design.reorderBlock(blocks,'unknown','a'),blocks);
for(const type of ['heading','button','divider','spacer'])assert.equal(site.normalizeDocument({pages:[{blocks:[site.newBlock(type)]}]}).pages[0].blocks[0].type,type);
const React=require('react'),render=require('react-dom/server').renderToStaticMarkup;const extra=load('components/BuilderExtraElements.js',{'../lib/site-builder':site,'./BuilderExtraElements.module.css':new Proxy({},{get:(_,k)=>String(k)})});const view=load('components/BuilderSiteView.js',{'../lib/site-builder':site,'../lib/builder-design':design,'./BuilderTemplateArt':()=>null,'./BuilderExtraElements':extra,'./SiteBuilder.module.css':new Proxy({},{get:(_,k)=>String(k)}),'next/link':({children,...props})=>React.createElement('a',props,children)}).default;const html=render(React.createElement(view,{name:'آزمون',document:result}));assert(html.includes('--block-mobile-title:24px'));assert(html.includes('data-design-background'));assert(html.includes('محتوای محفوظ'));assert(!html.includes('designSelectable'));
assert.equal(Object.keys(site.blockLabels).length,26);
for(const type of extra.extraElementTypes){const b=site.newBlock(type);const d=site.normalizeDocument({pages:[{blocks:[b]}]});assert.equal(d.pages[0].blocks[0].type,type);assert(render(React.createElement(view,{name:'آزمون',document:d})).includes(b.title));}
const injected={...site.newBlock('links'),items:['ناامن | javascript:alert(1)','امن | https://example.com']};const secure=render(React.createElement(extra.default,{block:injected}));assert(!secure.includes('javascript:'));assert(secure.includes('https://example.com'));
const faq=render(React.createElement(extra.default,{block:site.newBlock('faq')}));assert(faq.includes('<details>')&&faq.includes('<summary>'));
const progress=render(React.createElement(extra.default,{block:{...site.newBlock('progress'),items:['فارسی | ۸۰','بیش از سقف | 999','منفی | -2']}}));assert(progress.includes('value="80"'));assert(progress.includes('value="100"'));assert(progress.includes('value="0"'));
console.log('PASS: legacy compatibility, saved/mobile design round trip, safe CSS bounds, new elements and immutable reorder');
