import Link from 'next/link';
import { ArrowLeft, ArrowUpLeft, BarChart3, Bot, Boxes, Check, ChevronDown, CircleHelp, Clock3, Gauge, Layers3, MessageSquareText, RefreshCw, ShieldCheck, ShoppingCart, Sparkles, TrendingUp, UsersRound, Workflow } from 'lucide-react';

const services=[
  { icon: Gauge, code:'APU / قیمت‌گذاری', title:'به‌روزرسانی قیمت‌ها', description:'قیمت را از چند منبع پایش کن، قانون‌های دلخواهت را تعریف کن و تغییرها را پیش از اجرا بازبینی کن.', status:'محصول اصلی', active:true, href:'#apu' },
  { icon: MessageSquareText, code:'ENGAGEMENT / پیام‌ها', title:'صندوق پیام یکپارچه', description:'گفت‌وگوهای کانال‌های متصل را در یک فضای کاری ببین و پیگیری هر مکالمه را به تیم بسپار.', status:'در نقشهٔ راه' },
  { icon: ShoppingCart, code:'COMMERCE / سفارش‌ها', title:'مدیریت سفارش‌ها', description:'سفارش‌های ورودی را دسته‌بندی کن، وضعیت انجام را دنبال کن و قدم بعدی هر سفارش را روشن نگه دار.', status:'در نقشهٔ راه' },
  { icon: UsersRound, code:'CUSTOMERS / ارتباط با مشتری', title:'مدیریت مشتریان', description:'اطلاعات و سابقهٔ تعامل مشتری را کنار هم نگه دار تا پیگیری‌ها از بین پیام‌ها گم نشوند.', status:'در نقشهٔ راه' },
  { icon: Boxes, code:'CATALOG / محصول و موجودی', title:'کاتالوگ و موجودی', description:'اطلاعات محصول و موجودی را یک‌جا سامان بده و برای کانال‌های متصل آماده نگه دار.', status:'در نقشهٔ راه' },
  { icon: Bot, code:'AUTOMATION / فرایندها', title:'پاسخ‌گویی و اتوماسیون', description:'برای کارهای تکراری پاسخ‌ها و جریان‌های مشخص بساز؛ موارد حساس با تأیید تیم پیش می‌روند.', status:'در نقشهٔ راه' },
  { icon: BarChart3, code:'INSIGHTS / گزارش‌ها', title:'گزارش عملکرد', description:'نمایی روشن از تغییر قیمت، گفت‌وگوها و روند سفارش‌ها برای تصمیم‌گیری بهتر داشته باش.', status:'در نقشهٔ راه' },
  { icon: Workflow, code:'WORKFLOWS / اتصال سیستم‌ها', title:'اتوماسیون اختصاصی', description:'مرحله‌های تکراری بین ابزارهای کسب‌وکارت را به فرایندهای قابل پیگیری تبدیل کن.', status:'در نقشهٔ راه' },
];
const steps=[['۱','منبع قیمت را انتخاب کن','منبع قابل‌اعتماد بازار یا صفحه‌ی محصول را اضافه کن.'],['۲','محصول‌ها را تطبیق بده','قیمت فعلی را با داده‌ی منبع مقایسه کن.'],['۳','تغییر را بازبینی کن','پیشنهادهای غیرعادی را قبل از اجرا تأیید کن.']];
export default function Home(){return <>
<header className="site-header floating-header wrap" style={{backdropFilter:"blur(24px) saturate(160%)",WebkitBackdropFilter:"blur(24px) saturate(160%)"}}><Link href="/" className="brand" aria-label="دلسا، خانه"><img className="brand-mark" src="/delsa-mark.svg" alt=""/><span className="brand-word">DELSA</span></Link><nav aria-label="منوی اصلی"><a href="#services">سرویس‌ها</a><a href="#apu">APU</a><a href="#how">نحوه‌ی کار</a><Link href="/pricing">تعرفه</Link></nav><Link className="button small" href="/login">ورود به پنل <ArrowUpLeft size={17}/></Link></header>
<main>
<section className="cinematic-hero apu-hero"><div className="apu-hero-art" aria-hidden="true"><div className="apu-glow"/><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="floating-price price-one"><span>قیمت بازار</span><b>۵۱۵٬۰۰۰ <small>تومان</small></b><i>+۷٫۲٪</i></div><div className="floating-price price-two"><span>قیمت فروشگاه</span><b>۴۸۰٬۰۰۰ <small>تومان</small></b><i className="orange">↑ نیاز به بررسی</i></div><div className="price-chart"><svg viewBox="0 0 510 185" role="img" aria-label="روند نمونه تغییر قیمت"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#ff5a1f" stopOpacity=".32"/><stop offset="1" stopColor="#ff5a1f" stopOpacity="0"/></linearGradient></defs><path d="M0 155 C50 145 52 118 96 128 S153 86 196 103 S258 55 301 76 S364 94 405 48 S463 65 510 15 V185 H0Z" fill="url(#chartFill)"/><path d="M0 155 C50 145 52 118 96 128 S153 86 196 103 S258 55 301 76 S364 94 405 48 S463 65 510 15" fill="none" stroke="#ff7547" strokeWidth="3"/><circle cx="405" cy="48" r="5" fill="#f5f2ea" stroke="#ff5a1f" strokeWidth="3"/></svg><div className="chart-labels"><span>شروع پایش</span><span>اکنون</span></div></div><div className="orbit-dot dot-a"/><div className="orbit-dot dot-b"/></div>
<div className="cinematic-inner wrap"><div className="cinematic-label"><span className="cinematic-pulse"/> به‌روزرسانی خودکار قیمت · APU</div><h1 className="apu-headline">قیمت درست،<br/><em>در زمان درست.</em></h1><div className="cinematic-intro"><div><span className="cinematic-overline">قیمت‌های بازار را زیر نظر بگیر.</span><p>APU دلسا قیمت محصول‌ها را با منبع دلخواهت مقایسه می‌کند تا تغییرهای مهم را زودتر ببینی و با اطمینان تصمیم بگیری.</p></div><div className="hero-actions"><Link className="button primary" href="/signup">شروع با APU <ArrowUpLeft size={19}/></Link><a className="button cinematic-secondary" href="#how">چطور کار می‌کند؟ <ArrowLeft size={17}/></a></div></div><div className="hero-proof"><span><ShieldCheck size={16}/> تأیید پیش از تغییر</span><span><Clock3 size={16}/> پایش زمان‌بندی‌شده</span><span><Gauge size={16}/> کنترل در دست شماست</span></div></div><a className="hero-scroll" href="#apu" aria-label="پایین صفحه"><ChevronDown size={20}/></a></section>
<section id="apu" className="wrap apu-story"><div className="story-copy"><span className="eyebrow">APU / AUTOMATED PRICE UPDATES</span><h2>از پایش قیمت<br/>تا تصمیم مطمئن.</h2><p>تغییرات بازار را دستی و پراکنده دنبال نکن. یک مسیر ساده برای جمع‌آوری قیمت، تشخیص اختلاف و بازبینی تغییرات داشته باش.</p><ul><li><Check/> مقایسه‌ی قیمت با منابع مشخص</li><li><Check/> هشدار برای اختلاف‌های مهم</li><li><Check/> تأیید انسانی پیش از تغییر قیمت</li></ul><Link href="/signup" className="text-link">ساخت حساب رایگان <ArrowLeft size={16}/></Link></div><div className="apu-demo"><div className="demo-head"><div className="demo-title"><span className="demo-icon"><RefreshCw size={16}/></span><div><b>پایش قیمت</b><small>فروشگاه نمونه · اجرای آزمایشی</small></div></div><span className="live-tag"><i/> در حال پایش</span></div><div className="demo-stats"><div><small>محصول بررسی‌شده</small><b>۱۲۸</b></div><div><small>نیازمند بازبینی</small><b className="text-orange">۰۸</b></div><div><small>بدون تغییر</small><b>۱۲۰</b></div></div><div className="demo-line"><span>محصول</span><span>فروشگاه</span><span>منبع</span><span>وضعیت</span></div>{[['کرم آبرسان روزانه','۴۸۰٬۰۰۰','۵۱۵٬۰۰۰','بازبینی'],['شامپو بدون سولفات','۲۲۰٬۰۰۰','۲۲۸٬۰۰۰','تغییر جزئی'],['سرم ویتامین C','۳۹۰٬۰۰۰','۳۹۰٬۰۰۰','همسان']].map((x,i)=><div className="demo-line demo-product" key={x[0]}><span><b>{x[0]}</b><small>SKU-20{i+1}8</small></span><strong>{x[1]}</strong><strong>{x[2]}</strong><span className={'demo-status status-'+i}>{x[3]}</span></div>)}<div className="demo-foot"><CircleHelp size={14}/> اعداد نمایشی هستند؛ اتصال واقعی پس از راه‌اندازی فعال می‌شود.</div></div></section>
<section id="how" className="steps-section"><div className="wrap"><div className="section-head"><div><span className="eyebrow">ساده و شفاف</span><h2>سه گام تا کنترل قیمت‌ها</h2></div><p>APU تغییرها را برایت روشن می‌کند؛ تصمیم نهایی همیشه با توست.</p></div><div className="steps-grid">{steps.map(([num,title,copy])=><article key={num}><span className="step-number">{num}</span><span className="step-spark"><Sparkles size={18}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
<section id="services" className="wrap services-section" aria-labelledby="services-title"><div className="services-intro"><div><span className="eyebrow">ابزارهای دلسا</span><h2 id="services-title">از قیمت تا ارتباط با مشتری.</h2></div><p>APU نقطهٔ شروع دلساست. سرویس‌های دیگر هم در نقشهٔ راه‌اند تا کارهای روزمرهٔ فروش را در یک مسیر به هم وصل کنند.</p></div><div className="service-grid">{services.map((service)=>{const Icon=service.icon;return <article className={`service-card${service.active?' service-card-active':''}`} key={service.code}><div className="service-top"><span className="service-icon"><Icon size={19}/></span><span className={`service-status${service.active?' service-status-active':''}`}>{service.status}</span></div><div className="service-copy"><span className="service-code">{service.code}</span><h3>{service.title}</h3><p>{service.description}</p></div>{service.active?<Link className="service-link" href={service.href}>رفتن به بخش APU <ArrowLeft size={16}/></Link>:<span className="service-roadmap"><Layers3 size={14}/> در حال آماده‌سازی</span>}</article>})}</div></section>
<section className="wrap faq"><div className="section-head"><div><span className="eyebrow">پاسخ روشن</span><h2>سؤال‌های متداول</h2></div></div><details><summary>APU چه کاری انجام می‌دهد؟</summary><p>قیمت محصول‌ها را با منابعی که تعریف می‌کنی مقایسه می‌کند و اختلاف‌های مهم را برای بازبینی نمایش می‌دهد.</p></details><details><summary>آیا تغییر قیمت خودکار اعمال می‌شود؟</summary><p>در این نسخه تمرکز روی پایش و تأیید امن تغییرهاست. هیچ تغییری بدون اتصال و پیکربندی فروشگاه اعمال نمی‌شود.</p></details><details><summary>کدام ابزارها هم‌اکنون فعال‌اند؟</summary><p>فعلاً APU محصول اصلی دلساست. مدیریت سفارش، پیام‌ها و سایر بخش‌ها به‌زودی معرفی می‌شوند.</p></details></section>
<section className="wrap closing"><div><span className="eyebrow">DELSA APU</span><h2>قیمت‌ها را با دید باز مدیریت کن.</h2><p>حساب بساز و برای دسترسی به فضای APU آماده شو.</p></div><Link className="button primary" href="/signup">ساخت حساب <ArrowUpLeft size={19}/></Link></section></main>
<footer className="wrap footer"><Link href="/" className="brand"><img className="brand-mark" src="/delsa-mark.svg" alt=""/><span className="brand-word">DELSA</span></Link><span>Digital Engagement Layer System Automation</span><Link href="/admin/login">ورود مدیر</Link></footer>
</>}
