import Link from 'next/link';
import {ArrowUpLeft, ArrowLeft, RefreshCw, MessagesSquare, SlidersHorizontal, Check, Layers3} from 'lucide-react';
export default function Home(){return <>
  <header className="site-header wrap"><Link href="/" className="brand" aria-label="دلسا، صفحه اصلی">delsa<span>●</span></Link><nav aria-label="منوی اصلی"><a href="#products">راهکارها</a><a href="#process">روش کار</a><a href="#faq">پرسش‌ها</a></nav><Link className="button small" href="/dashboard">مشاهده داشبورد <ArrowUpLeft size={17}/></Link></header>
  <main><section className="hero wrap"><div className="eyebrow"><span className="line"/> برای کسب‌وکاری که جلو می‌رود</div><h1>کارهای تکراری را<br/>به <em>دلسا</em> بسپار.</h1><div className="hero-bottom"><p>از به‌روزرسانی قیمت‌ها تا ارتباط با مشتری؛<br/>کسب‌وکارت را با اتوماسیون جلو ببر.</p><Link className="button primary" href="/dashboard">تجربه داشبورد آزمایشی <ArrowUpLeft size={21}/></Link></div><div className="hero-index"><span>DELSA / AUTOMATION</span><span>۰۱ — کمتر درگیر، بیشتر متمرکز</span></div></section>
  <section id="products" className="wrap products"><div className="section-head"><div><span className="eyebrow">راهکارهای دلسا</span><h2>یک قدم از کارهای روزمره جلوتر.</h2></div><span className="muted">ابزار متناسب با جریان کار تو</span></div><div className="product-grid"><article className="product featured"><div className="product-top"><RefreshCw size={30}/><span className="tag">APU</span></div><h3>قیمت‌ها به‌روز.<br/>خیالت راحت‌تر.</h3><p>به‌روزرسانی قیمت و موجودی فروشگاه بر اساس منابع تعریف‌شده، با امکان بررسی تغییرات و گزارش اجرا.</p><Link href="/dashboard?tab=apu">بررسی محیط APU <ArrowLeft size={20}/></Link></article><article className="product"><div className="product-top"><MessagesSquare size={30}/><span className="tag">ارتباط با مشتری</span></div><h3>گفت‌وگوها،<br/>در یک فضای مشترک.</h3><p>طرح پنل یکپارچه برای مدیریت پیام‌ها و پاسخ‌گویی در بله، ایتا، روبیکا و سروش.</p><Link href="/dashboard?tab=channels">مشاهده کانال‌ها <ArrowLeft size={20}/></Link></article></div></section>
  <section id="process" className="wrap process"><div><span className="eyebrow">از نیاز تا اتوماسیون</span><h2>جریان کار تو.<br/>با اجرای دلسا.</h2></div><div className="steps">{[['۰۱','نیازت را مشخص کن','فروشگاه، منابع قیمت و کانال‌های ارتباطی را انتخاب کن.'],['۰۲','قواعد را تنظیم کن','محدوده تغییرات و موارد نیازمند بررسی را تعیین کن.'],['۰۳','نتیجه را دنبال کن','گزارش اجرا و موارد نیازمند توجه را در داشبورد ببین.']].map(([n,t,p])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div></article>)}</div></section>
  <section id="faq" className="wrap faq"><h2>قبل از شروع</h2><details><summary>آیا همین حالا می‌توانم داشبورد را ببینم؟</summary><p>بله. محیط آزمایشی بدون ثبت‌نام قابل بررسی است. اطلاعات نمونه‌اند و هیچ تغییری در فروشگاه یا پیام‌رسان واقعی ایجاد نمی‌شود.</p></details><details><summary>APU برای چه فروشگاه‌هایی در نظر گرفته شده؟</summary><p>تمرکز اولیه بر اتوماسیون فروشگاه‌های دیجی‌فای است. پیش از فعال‌سازی، ساختار فروشگاه و منابع قیمت باید بررسی شوند.</p></details><details><summary>اتصال پیام‌رسان‌ها فعال است؟</summary><p>در این پیش‌نمایش فقط رابط کانال‌ها آماده است. اتصال واقعی پس از پیکربندی سرویس و دسترسی‌های هر کانال انجام می‌شود.</p></details></section>
  <section className="wrap closing"><Layers3 size={32}/><h2>دلسا را از نزدیک ببین.</h2><Link className="button primary" href="/dashboard">ورود به محیط آزمایشی <ArrowUpLeft size={20}/></Link></section></main>
  <footer className="wrap footer"><Link href="/" className="brand">delsa<span>●</span></Link><span>اتوماسیون، برای فرصت‌های بیشتر.</span><span>نسخه اولیه · پیش‌نمایش</span></footer>
</>;}
