'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Search,Send,RefreshCw} from 'lucide-react';
import {createClient} from '../lib/supabase/client';
import ChatMessage from './ChatMessage';
const formatTime=value=>new Intl.DateTimeFormat('fa-IR',{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Tehran'}).format(new Date(value));
const normalize=value=>String(value||'').replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).toLowerCase().replace(/\s+/g,' ').trim();
export default function AdminSupport(){
 const db=useMemo(()=>createClient(),[]),[threads,setThreads]=useState([]),[selected,setSelected]=useState(null),[body,setBody]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[viewer,setViewer]=useState(null),loading=useRef(false);
 const load=useCallback(async()=>{if(loading.current)return;loading.current=true;try{const {data:{user}}=await db.auth.getUser();if(!user)throw new Error('auth');setViewer(user.id);const [customer,visitors,visitorMessages,profiles]=await Promise.all([
 db.from('support_messages').select('*').order('created_at',{ascending:false}).limit(1000),
 db.from('visitor_chats').select('id,full_name,phone,created_at,updated_at').order('updated_at',{ascending:false}).limit(500),
 db.from('visitor_chat_messages').select('*').order('created_at',{ascending:false}).limit(1000),
 db.from('profiles').select('id,full_name,phone,role').order('created_at',{ascending:false}).limit(1000)]);
 if([customer,visitors,visitorMessages,profiles].some(r=>r.error))throw new Error('load');
 const map=new Map();for(const p of profiles.data){if(p.role==='admin')continue;const key='customer:'+p.id;map.set(key,{key,type:'customer',id:p.id,title:p.full_name||'مشتری بدون نام',phone:p.phone||'',messages:[]})}
 for(const m of customer.data){if(m.hidden_by?.includes(user.id))continue;const key='customer:'+m.user_id;if(!map.has(key))map.set(key,{key,type:'customer',id:m.user_id,title:'مشتری',phone:'',messages:[]});map.get(key).messages.push(m)}
 for(const c of visitors.data)map.set('visitor:'+c.id,{key:'visitor:'+c.id,type:'visitor',id:c.id,title:c.full_name||'بازدیدکننده · وب‌سایت',phone:c.phone||'',messages:[]});
 for(const m of visitorMessages.data){const t=map.get('visitor:'+m.chat_id);if(t&&!m.hidden_by?.includes(user.id))t.messages.push(m)}
 const all=[...map.values()].map(t=>({...t,messages:t.messages.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)||a.id.localeCompare(b.id))})).sort((a,b)=>new Date(b.messages.at(-1)?.created_at||0)-new Date(a.messages.at(-1)?.created_at||0)||a.title.localeCompare(b.title,'fa'));setThreads(all);setSelected(current=>current&&all.some(t=>t.key===current)?current:all[0]?.key||null);setError('');}catch{setError('دریافت گفت‌وگوها انجام نشد.')}finally{loading.current=false}},[db]);
 useEffect(()=>{load();const timer=setInterval(()=>{if(document.visibilityState==='visible')load()},5000);return()=>clearInterval(timer)},[load]);
 const active=threads.find(t=>t.key===selected),filtered=threads.filter(t=>{const q=normalize(query);return !q||normalize(t.title+' '+t.phone).includes(q)||t.messages.some(m=>normalize(m.body).includes(q))});
 async function reply(e){e.preventDefault();const value=body.trim();if(!value||!active||busy||!viewer)return;setBusy(true);setError('');try{const result=active.type==='customer'?await db.from('support_messages').insert({user_id:active.id,sender_id:viewer,sender_role:'admin',body:value}):await db.from('visitor_chat_messages').insert({chat_id:active.id,sender_id:viewer,sender_role:'admin',body:value});if(result.error)throw result.error;setBody('');await load()}catch{setError('پیام ثبت نشد. دوباره تلاش کنید.')}finally{setBusy(false)}}
 async function messageAction(m,action,value){const {error}=await db.rpc('support_message_action',{p_kind:active.type,p_id:m.id,p_action:action,p_body:value});if(error)throw error;await load()}
 return <div className="admin-support"><div className="admin-support-top"><p>مشتری را جست‌وجو کنید؛ حتی اگر هنوز پیامی نداده باشد.</p><button type="button" onClick={load}><RefreshCw size={15}/> تازه‌سازی</button></div><label className="support-search"><Search size={18}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="جست‌وجوی نام، شماره یا متن پیام…" aria-label="جست‌وجوی مشتری و گفت‌وگو"/></label>{error&&<p className="admin-form-error" role="alert">{error}</p>}<div className="admin-support-layout"><div className="admin-support-list">{filtered.length?filtered.map(t=><button type="button" key={t.key} className={selected===t.key?'active':''} onClick={()=>{setSelected(t.key);setBody('')}}><div className="support-thread-title"><strong>{t.title}</strong><b className={'chat-label '+t.type}>{t.type==='customer'?'مشتری':'بازدیدکننده'}</b></div><small dir="ltr">{t.phone||'شماره ثبت نشده'}</small><span>{t.messages.at(-1)?.body||'شروع گفت‌وگوی جدید'}</span></button>):<p>نتیجه‌ای پیدا نشد.</p>}</div><div className="admin-support-conversation">{active?<><div className="admin-support-contact"><div><strong>{active.title}</strong><b className={'chat-label '+active.type}>{active.type==='customer'?'مشتری':'بازدیدکننده'}</b></div><span dir="ltr">{active.phone||'شماره هنوز دریافت نشده'}</span></div><div className="admin-support-messages">{active.messages.length?active.messages.map(m=><article key={m.id} className={m.sender_role==='admin'?'admin-reply':''}><small>{m.sender_role==='admin'?'شما':m.sender_role==='system'?'پیام خودکار':active.title} · {formatTime(m.created_at)}</small><ChatMessage message={m} canEdit={m.sender_role==='admin'&&(!m.sender_id||m.sender_id===viewer)} canDeleteAll={m.sender_role!=='system'} maxLength={active.type==='visitor'?2000:4000} onAction={(action,value)=>messageAction(m,action,value)}/></article>):<p className="support-empty">هنوز پیامی نیست. اولین پیام را شما بفرستید.</p>}</div><form className="admin-support-compose" onSubmit={reply}><textarea required maxLength={active.type==='visitor'?2000:4000} rows={2} value={body} onChange={e=>setBody(e.target.value)} placeholder="پیام خود را بنویسید…" aria-label="پیام مدیر"/><button type="submit" disabled={busy||!body.trim()}><Send size={16}/> ارسال پیام</button></form></>:<p>مشتری یا گفت‌وگویی را انتخاب کنید.</p>}</div></div></div>
}
