'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {BarChart3,ChevronDown,GripVertical,LayoutGrid,LockKeyhole,Plus,ShieldCheck,UsersRound,Eye,EyeOff} from 'lucide-react';
import PlatformCredentialsAdmin from './PlatformCredentialsAdmin';
import StoreProductsAdmin from './StoreProductsAdmin';
const ORDER=['overview','credentials','products','add-customer','users','security'];
const TITLES={overview:'نمای کلی',credentials:'اطلاعات مشتری و پلتفرم‌ها',products:'محصولات فروشگاه','add-customer':'افزودن مشتری',users:'مدیریت مشتری‌ها',security:'امنیت و دسترسی'};
const DIGITS='۰۱۲۳۴۵۶۷۸۹';
function phone(value){let v=String(value||'').replace(/[۰-۹]/g,d=>String(DIGITS.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).trim().replace(/[\s()-]/g,'');if(v.startsWith('00'))v='+'+v.slice(2);if(/^09\d{9}$/.test(v))return '+98'+v.slice(1);if(/^9\d{9}$/.test(v))return '+98'+v;if(/^98\d{10}$/.test(v))return '+'+v;return /^\+\d{8,15}$/.test(v)?v:'';}
function displayPhone(u){let value=u.phone||String(u.email||'').match(/^phone-(\d+)@delsa\.invalid$/i)?.[1]||'';let d=String(value).replace(/\D/g,'');if(d.startsWith('98')&&d.length===12)return '0'+d.slice(2);if(d.length===11&&d.startsWith('0'))return d;if(d.length===10&&d.startsWith('9'))return '0'+d;return value||'—';}
function AddCustomer({onCreated}){const [form,S]=useState({name:'',phone:'',password:'',confirmation:''});const [show,A]=useState(false),[show2,B]=useState(false),[busy,C]=useState(false),[error,E]=useState(''),[success,F]=useState('');async function submit(e){e.preventDefault();C(true);E('');F('');const normalized=phone(form.phone);if(!normalized){E('شماره تماس را به شکل 09962958692 وارد کنید.');C(false);return;}if(form.password!==form.confirmation){E('رمزهای عبور با هم مطابقت ندارند.');C(false);return;}try{const r=await fetch('/api/admin/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.name.trim(),phone:normalized,password:form.password,passwordConfirmation:form.confirmation})});const data=await r.json();if(!r.ok)throw new Error(data.error||'ساخت حساب انجام نشد.');F('حساب مشتری ساخته شد و در فهرست مشتری‌ها قرار گرفت.');S({name:'',phone:'',password:'',confirmation:''});onCreated();}catch(err){E(err.message||'ساخت حساب انجام نشد.');}finally{C(false);}}
return <div className="admin-add-customer"><p className="admin-form-intro">همان فیلدهای ثبت‌نام مشتری را تکمیل کنید. حساب با نقش «کاربر» ساخته می‌شود.</p><form className="admin-customer-form" onSubmit={submit}><label>نام و نام خانوادگی<input required maxLength={120} autoComplete="name" value={form.name} onChange={e=>S({...form,name:e.target.value})} placeholder="نام مشتری"/></label><label>شماره تماس<input required type="tel" inputMode="tel" autoComplete="tel" value={form.phone} onChange={e=>S({...form,phone:e.target.value})} placeholder="09962958692" dir="ltr"/></label><label>رمز عبور<div className="admin-password-wrap"><input required minLength={8} autoComplete="new-password" type={show?'text':'password'} value={form.password} onChange={e=>S({...form,password:e.target.value})} placeholder="حداقل ۸ نویسه"/><button type="button" aria-label={show?'مخفی کردن رمز عبور':'نمایش رمز عبور'} onClick={()=>A(v=>!v)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><label>تکرار رمز عبور<div className="admin-password-wrap"><input required minLength={8} autoComplete="new-password" type={show2?'text':'password'} value={form.confirmation} onChange={e=>S({...form,confirmation:e.target.value})} placeholder="رمز را دوباره وارد کنید"/><button type="button" aria-label={show2?'مخفی کردن رمز عبور':'نمایش رمز عبور'} onClick={()=>B(v=>!v)}>{show2?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{error&&<p className="admin-form-error" role="alert">{error}</p>}{success&&<p className="admin-form-success" role="status">{success}</p>}<button className="credential-submit" type="submit" disabled={busy}>{busy?'در حال ساخت…':<><Plus size={17}/> ساخت حساب مشتری</>}</button></form></div>;}
function Widget({id,title,children,layout,span,onSpan,collapsed,onToggle,onDrop}){return <section className="admin-widget" style={{'--widget-span':Math.min(layout,span)}} draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',id);e.dataTransfer.effectAllowed='move';}} onDragOver={e=>e.preventDefault()} onDrop={e=>onDrop(e,id)}><header className="admin-widget-header"><span className="admin-widget-drag" title="برای جابه‌جایی بکشید"><GripVertical size={18}/></span><button className="admin-widget-title" type="button" aria-expanded={!collapsed} onClick={()=>onToggle(id)}><span>{title}</span><ChevronDown className={collapsed?'collapsed':''} size={18}/></button><div className="admin-widget-width" aria-label={'عرض بلوک '+title}>{[1,2,3].filter(n=>n<=layout).map(n=><button key={n} type="button" className={span===n?'active':''} aria-pressed={span===n} onClick={()=>onSpan(id,n)}>{n}</button>)}</div></header>{!collapsed&&<div className="admin-widget-content">{children}</div>}</section>;}
export default function AdminDashboardClient({users=[],products=[]}){const router=useRouter();const [layout,setLayout]=useState(3),[order,setOrder]=useState(ORDER),[spans,setSpans]=useState({overview:3,credentials:3,products:2,'add-customer':1,users:2,security:1}),[collapsed,setCollapsed]=useState({}),[hydrated,setHydrated]=useState(false),[notice,setNotice]=useState('');useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('delsa-admin-layout')||'{}');if([1,2,3].includes(s.layout))setLayout(s.layout);if(Array.isArray(s.order)&&s.order.length===ORDER.length&&ORDER.every(id=>s.order.includes(id)))setOrder(s.order);if(s.spans)setSpans(v=>({...v,...s.spans}));if(s.collapsed)setCollapsed(s.collapsed);}catch{}setHydrated(true);},[]);useEffect(()=>{if(hydrated)localStorage.setItem('delsa-admin-layout',JSON.stringify({layout,order,spans,collapsed}));},[hydrated,layout,order,spans,collapsed]);function move(e,target){e.preventDefault();const source=e.dataTransfer.getData('text/plain');if(!source||source===target||!order.includes(source)||!order.includes(target))return;setOrder(v=>{const a=v.filter(x=>x!==source);a.splice(a.indexOf(target),0,source);return a;});}
const blocks={overview:<div className="admin-summary-grid"><article><UsersRound/><span>حساب‌های ثبت‌شده</span><strong>{users.length.toLocaleString('fa-IR')}</strong><small>فهرست تا ۵۰۰ حساب اخیر</small></article><article><BarChart3/><span>وضعیت APU</span><strong>در حال آماده‌سازی</strong><small>اتصال منبع قیمت هنوز انجام نشده</small></article><article><ShieldCheck/><span>نقش شما</span><strong>مدیر سامانه</strong><small>دسترسی مدیر بررسی شده است</small></article></div>,credentials:<PlatformCredentialsAdmin/>,products:<StoreProductsAdmin products={products} onCreated={()=>{setNotice('محصول جدید اضافه شد.');router.refresh();}}/>,'add-customer':<AddCustomer onCreated={()=>{setNotice('حساب جدید در فهرست اضافه شد.');router.refresh();}}/>,users:<div className="admin-users-list">{users.length?<div className="users-table"><div className="users-row users-head"><span>کاربر</span><span>شماره تماس</span><span>نقش</span><span>تاریخ عضویت</span></div>{users.map(u=><div className="users-row" key={u.id}><span><UsersRound size={16}/>{u.full_name||'بدون نام'}</span><span dir="ltr">{displayPhone(u)}</span><span className={u.role==='admin'?'role-admin':'role-user'}>{u.role==='admin'?'مدیر':'کاربر'}</span><span>{u.created_at?new Date(u.created_at).toLocaleDateString('fa-IR'):'—'}</span></div>)}</div>:<p className="empty-users">هنوز حساب مشتری ثبت نشده است.</p>}</div>,security:<div className="admin-security-note"><LockKeyhole size={20}/><div><b>حساب‌های تازه نقش کاربر می‌گیرند</b><p>ساخت مدیر از این فرم ممکن نیست؛ ارتقای نقش فقط با دسترسی امن پایگاه داده انجام می‌شود.</p></div></div>};
return <div className="panel-main admin-main"><div className="panel-greeting"><span className="eyebrow">مدیریت دلسا</span><h1>داشبورد مدیریت</h1><p>مشتری‌ها، اطلاعات اتصال و وضعیت سامانه را از اینجا مدیریت کنید.</p></div>{notice&&<div className="admin-created-notice" role="status">{notice}</div>}<div className="admin-layout-toolbar"><span><LayoutGrid size={17}/> تعداد ستون‌ها</span>{[1,2,3].map(n=><button key={n} type="button" className={layout===n?'active':''} aria-pressed={layout===n} onClick={()=>setLayout(n)}>{n} ستون</button>)}</div><div className="admin-widgets" style={{'--admin-columns':layout,'--tablet-columns':Math.min(layout,2)}}>{order.map(id=><Widget key={id} id={id} title={TITLES[id]} layout={layout} span={spans[id]||1} onSpan={(k,v)=>setSpans(s=>({...s,[k]:v}))} collapsed={Boolean(collapsed[id])} onToggle={k=>setCollapsed(s=>({...s,[k]:!s[k]}))} onDrop={move}>{blocks[id]}</Widget>)}</div><div className="admin-layout-help">برای جابه‌جایی بلوک، آن را بکشید. عنوان هر بلوک آن را باز و بسته می‌کند و شماره‌های کنارش پهنا را تغییر می‌دهند.</div></div>;}

