'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Play,Pause,RotateCcw,ShoppingBag,TrendingUp,FileText,Upload,RefreshCw,MessageCircle,Layers} from 'lucide-react';
import styles from './AnimationStory.module.css';
const scenes=[
['هوک: فروش امروز و خرید فردا',0,120,'امروز فروختی…','فردا چی؟','می‌تونی همون جنس رو دوباره بخری؟',ShoppingBag],
['افزایش دلار و ضرر پنهان',120,240,'دلار بالا رفت.','قیمت تو جا موند!','این فاصله یعنی ضرر پنهان؛ در خرید بعدی خودش رو نشون می‌ده.',TrendingUp],
['معرفی APU و آپلود فاکتور',240,320,'شروع با یک','فاکتور.','با اِی پی یو، فاکتور خریدت نقطهٔ شروع چرخه است.',Upload],
['فاکتورخوانی و تنظیم قیمت با دلار',320,492,'مبنا ثبت می‌شه.','قیمت همراه بازار.','خواندن فاکتور، ثبت مبنای قیمت و تنظیم قیمت‌ها با نوسانات دلار تا فاکتور بعدی.',TrendingUp],
['رسیدن فاکتور جدید',492,544,'خرید جدید؟','مبنای جدید!','فاکتور خرید بعدی که رسید، وقت تازه کردن مبناست.',FileText],
['آپلود در داشبورد و تازه‌شدن مبنا',544,660,'توی داشبوردت','آپلودش کن.','فاکتور تازه، مبنای تازه؛ چرخه ادامه پیدا می‌کنه.',Upload],
['«فاکتور با تو؛ به‌روزرسانی با APU»',660,736,'فاکتور با تو.','به‌روزرسانی با APU.','یک چرخهٔ پیوسته از خرید تا تنظیم قیمت.',RefreshCw],
['معرفی روش‌های دیگر',736,828,'این فقط','یکی از روش‌هاست!','سیستم اِی پی یو، مسیرهای بیشتری برای کار با قیمت‌ها دارد.',Layers],
['دعوت به کامنت',828,899,'برای مشاوره،','«اِی پی یو»','زیر پست کامنت کن؛ اینجا هم می‌تونی از گفت‌وگوی آنلاین با ما ارتباط بگیری.',MessageCircle]
];
const fa=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);const time=n=>fa(Number((n/20).toFixed(2)));
export default function AnimationStory(){const [frame,setFrame]=useState(0),[playing,setPlaying]=useState(false);const ref=useRef(0);useEffect(()=>{ref.current=frame},[frame]);useEffect(()=>{if(!playing)return;let id;const base=ref.current,start=performance.now();function tick(now){const next=Math.min(898,base+Math.floor((now-start)/50));setFrame(next);if(next===898){setPlaying(false);return}id=requestAnimationFrame(tick)}id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[playing]);const index=scenes.findIndex(s=>frame>=s[1]&&frame<s[2]),s=scenes[index],Icon=s[6];function seek(n){setPlaying(false);setFrame(n)}function toggle(){if(playing)setPlaying(false);else{if(frame===898){ref.current=0;setFrame(0)}setPlaying(true)}}
return <main className={styles.page}><header className={styles.header}><Link href="/" className={styles.brand}>DELSA <span>/ MOTION LAB</span></Link><Link href="/">بازگشت به سایت ↗</Link></header><section className={styles.intro}><span className={styles.eyebrow}>روایت تصویری اِی پی یو / ۰۱</span><h1>از فاکتور تا قیمت.<br/><em>در حرکت.</em></h1><p>یک روایت کلاژ و اینفوگرافیک در ۹ سکانس؛ سکانس دلخواهت را انتخاب کن یا کل مسیر را پخش کن.</p><div className={styles.metrics}><span><b>۲۰</b> فریم / ثانیه</span><span><b>۸۹۹</b> فریم</span><span><b>۴۴٫۹۵</b> ثانیه</span></div></section>
<section className={styles.player} aria-label="پخش روایت تصویری"><div className={`${styles.stage} ${playing?styles.running:''}`}><div className={styles.grid}/><span className={styles.corner}>DELSA / APU</span><span className={styles.number}>{fa(index+1).padStart(2,'۰')}</span><div key={index} className={styles.scene}><div className={styles.art} aria-hidden="true"><span className={styles.tape}/><div className={styles.paper}><FileText size={46}/><b>فاکتور خرید</b><i/><i/><i/><span>APU ✓</span></div><div className={styles.sticker}><Icon size={66} strokeWidth={1.6}/></div><div className={styles.chart}><span>قیمت / بازار</span><svg viewBox="0 0 240 100"><path d="M5 85L40 70L75 77L110 44L145 50L180 24L230 7" fill="none" stroke="currentColor" strokeWidth="7"/></svg></div><span className={styles.star}>✳</span><span className={styles.arrow}>↗</span></div><div className={styles.copy}><span className={styles.tag}>{s[0]}</span><h2>{s[3]}<br/><em>{s[4]}</em></h2><p>{s[5]}</p>{index===5&&<Link href="/dashboard" className={styles.cta}>رفتن به داشبورد <Upload size={16}/></Link>}{index===8&&<button className={styles.cta} onClick={()=>window.dispatchEvent(new CustomEvent('delsa:open-chat'))}>گفت‌وگوی آنلاین <MessageCircle size={16}/></button>}</div></div><span className={styles.frame}>FRAME {String(frame).padStart(3,'0')} / 898</span><span className={styles.caption}>کلاژ / اینفوگرافیک / حرکت</span></div><div className={styles.controls}><button onClick={toggle} aria-label={playing?'توقف':'پخش'}>{playing?<Pause size={20}/>:<Play size={20}/>} {playing?'توقف':'پخش روایت'}</button><button onClick={()=>seek(0)} aria-label="شروع دوباره"><RotateCcw size={19}/></button><input aria-label="موقعیت پخش برحسب فریم" type="range" min="0" max="898" value={frame} onChange={e=>seek(Number(e.target.value))}/><span>{time(frame)} / ۴۴٫۹۵ ثانیه</span></div><div className={styles.segments}>{scenes.map((x,i)=><button key={x[1]} className={i===index?styles.active:''} style={{flex:x[2]-x[1]}} onClick={()=>seek(x[1])} aria-label={`سکانس ${i+1}: ${x[0]}`} aria-pressed={i===index}>{fa(i+1)}</button>)}</div></section>
<section className={styles.timeline}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>نقشهٔ روایت</span><h2>۹ سکانس. یک چرخه.</h2></div><span>روی هر کارت بزن و همان بخش را ببین.</span></div><div className={styles.cards}>{scenes.map((x,i)=>{const CardIcon=x[6];return <button key={x[1]} onClick={()=>{seek(x[1]);document.querySelector(`.${styles.player}`)?.scrollIntoView({behavior:'smooth',block:'center'})}} className={i===index?styles.selected:''}><span className={styles.cardNumber}>{fa(i+1).padStart(2,'۰')}</span><CardIcon size={25}/><h3>{x[0]}</h3><span>{time(x[1])} تا {time(x[2])} ثانیه</span><small>{fa(x[1])}–{fa(x[2]-1)} / {fa(x[2]-x[1])} فریم</small></button>})}</div></section><details className={styles.tableSection}><summary>جدول دقیق زمان‌بندی و فریم‌ها</summary><div className={styles.tableScroll}><table><thead><tr><th>بخش</th><th>زمان (ثانیه)</th><th>تعداد فریم</th><th>فریم شروع تا پایان</th></tr></thead><tbody>{scenes.map(x=><tr key={x[1]}><td>{x[0]}</td><td>{time(x[1])}–{time(x[2])}</td><td>{fa(x[2]-x[1])}</td><td>{fa(x[1])}–{fa(x[2]-1)}</td></tr>)}</tbody><tfoot><tr><th>کل ویدیو</th><th>۴۴٫۹۵ ثانیه</th><th>۸۹۹</th><th>۰–۸۹۸</th></tr></tfoot></table></div></details><p className={styles.note}>این صفحه روایت تصویری روش کار APU است. بارگذاری فاکتور فعال است؛ فاکتورخوانی خودکار و تنظیم قیمت با دلار در مسیر توسعه قرار دارند.</p><footer className={styles.footer}><Link href="/">DELSA</Link><span>فاکتور با تو. به‌روزرسانی با اِی پی یو.</span></footer></main>}
