'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {FileUp,ImagePlus,Mic,Send,Square,X} from 'lucide-react';
import {createClient} from '../lib/supabase/client';
const LIMIT=20*1024*1024;
const ACCEPT='.pdf,.png,.jpg,.jpeg,.webp,.gif,.txt,.csv,.xlsx,.xls,.docx,.mp3,.m4a,.ogg,.wav,.webm,.mp4';
const MIME={pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',txt:'text/plain',csv:'text/csv',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',xls:'application/vnd.ms-excel',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',mp3:'audio/mpeg',m4a:'audio/mp4',ogg:'audio/ogg',wav:'audio/wav',webm:'audio/webm',mp4:'video/mp4'};
function Attachment({message}){
 const [url,setUrl]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function open(){setBusy(true);setError('');try{const {data,error}=await createClient().storage.from('apu-attachments').createSignedUrl(message.file_path,3600,{download:message.file_name});if(error)throw error;setUrl(data.signedUrl)}catch{setError('دریافت فایل انجام نشد. دوباره تلاش کنید.')}finally{setBusy(false)}}
 const audio=message.mime_type?.startsWith('audio/'),image=message.mime_type?.startsWith('image/');
 return <div className="apu-attachment"><strong>{message.kind==='invoice'?'فاکتور: ':''}{message.file_name}</strong><small>{(message.file_size/1024/1024).toLocaleString('fa-IR',{maximumFractionDigits:2})} مگابایت</small>{url?<>{image&&<img src={url} alt={message.file_name}/>} {audio&&<audio controls src={url} preload="none"/>}<a href={url} target="_blank" rel="noreferrer">دریافت فایل</a><button type="button" onClick={open} disabled={busy}>تازه‌سازی لینک</button></>:<button type="button" disabled={busy} onClick={open}>{busy?'در حال دریافت…':audio?'پخش پیام صوتی':image?'نمایش عکس':'دریافت فایل'}</button>}{error&&<small role="alert">{error}</small>}</div>
}
export default function ApuWorkspace({customerId,admin=false}){
 const db=useMemo(()=>createClient(),[]),[messages,setMessages]=useState([]),[body,setBody]=useState(''),[file,setFile]=useState(null),[kind,setKind]=useState('attachment'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[preview,setPreview]=useState('');
 const input=useRef(null),starting=useRef(false),recorder=useRef(null),media=useRef(null),chunks=useRef([]),timer=useRef(null),alive=useRef(true),running=useRef(false),stream=useRef(null),pinned=useRef(true);
 const load=useCallback(async()=>{if(running.current)return;running.current=true;try{const {data,error}=await db.from('apu_messages').select('*').eq('user_id',customerId).order('created_at',{ascending:false}).limit(200);if(error)throw error;if(alive.current){setMessages(data.reverse());setError('')}}catch{if(alive.current)setError('دریافت گفت‌وگوی APU انجام نشد.')}finally{running.current=false}},[db,customerId]);
 useEffect(()=>{alive.current=true;load();const interval=setInterval(()=>{if(document.visibilityState==='visible')load()},5000);return()=>{alive.current=false;clearInterval(interval);clearInterval(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();media.current?.getTracks().forEach(t=>t.stop())}},[load]);
 useEffect(()=>{if(stream.current&&pinned.current)stream.current.scrollTop=stream.current.scrollHeight},[messages.length]);
 useEffect(()=>{if(!file)return;const url=URL.createObjectURL(file);setPreview(url);return()=>{URL.revokeObjectURL(url);setPreview('')}},[file]);
 function select(value,type){setError('');if(!value)return;if(value.size===0||value.size>LIMIT){setError('فایل باید بین ۱ بایت و ۲۰ مگابایت باشد.');return}if(!MIME[value.name.split('.').at(-1)?.toLowerCase()]){setError('این نوع فایل پشتیبانی نمی‌شود.');return}setFile(value);setKind(type)}
 function choose(type,accept){if(busy||recording)return;setKind(type);input.current.accept=accept;input.current.value='';input.current.click()}
 async function startRecording(){if(busy||recording||starting.current)return;setError('');if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('ضبط صدا در این مرورگر پشتیبانی نمی‌شود؛ فایل صوتی را بارگذاری کنید.');return}starting.current=true;try{const tracks=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){tracks.getTracks().forEach(t=>t.stop());return}media.current=tracks;const mime=['audio/webm','audio/mp4','audio/ogg'].find(t=>MediaRecorder.isTypeSupported(t));const r=new MediaRecorder(tracks,mime?{mimeType:mime}:undefined);recorder.current=r;chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{clearInterval(timer.current);tracks.getTracks().forEach(t=>t.stop());if(!alive.current)return;setRecording(false);const type=r.mimeType.split(';')[0],ext=type.includes('mp4')?'m4a':type.includes('ogg')?'ogg':'webm';select(new File(chunks.current,['voice',Date.now()].join('-')+'.'+ext,{type}),'attachment')};r.start(1000);setRecording(true);setSeconds(0);let elapsed=0;timer.current=setInterval(()=>{elapsed++;setSeconds(elapsed);if(elapsed>=180&&r.state==='recording')r.stop()},1000)}catch{media.current?.getTracks().forEach(t=>t.stop());setError('دسترسی میکروفون ممکن نشد. مجوز مرورگر را بررسی کنید یا فایل صوتی بفرستید.')}finally{starting.current=false}}
 async function send(e){e.preventDefault();if(busy||recording||(!body.trim()&&!file))return;setBusy(true);setError('');let path;try{const {data:{user},error}=await db.auth.getUser();if(error||!user)throw Error('auth');let attachment={};if(file){const ext=file.name.split('.').at(-1).toLowerCase();path=customerId+'/'+crypto.randomUUID()+'.'+ext;const uploaded=await db.storage.from('apu-attachments').upload(path,file,{contentType:MIME[ext],upsert:false});if(uploaded.error)throw uploaded.error;attachment={file_path:path,file_name:file.name.slice(0,240),file_size:file.size,mime_type:MIME[ext]}}const inserted=await db.from('apu_messages').insert({user_id:customerId,sender_id:user.id,sender_role:admin?'admin':'customer',body:body.trim(),kind:file?kind:'message',...attachment}).select().single();if(inserted.error)throw inserted.error;setMessages(v=>[...v,inserted.data]);pinned.current=true;setBody('');setFile(null)}catch{if(path)await db.storage.from('apu-attachments').remove([path]);setError('ارسال انجام نشد. اتصال و فعال بودن اشتراک APU را بررسی کنید؛ فایل انتخاب‌شده حفظ شده است.')}finally{setBusy(false)}}
 return <section className="apu-workspace"><div className="apu-workspace-heading"><div><span>APU</span><h2>{admin?'گفت‌وگو و فایل‌های APU مشتری':'سیستم APU'}</h2><p>فاکتور، عکس، فایل و پیام صوتی را از همین‌جا ارسال کنید.</p></div><FileUp size={25}/></div><div className="apu-chat-stream" ref={stream} onScroll={e=>{const el=e.currentTarget;pinned.current=el.scrollHeight-el.clientHeight-el.scrollTop<60}} aria-live="polite">{messages.length?messages.map(m=><article key={m.id} className={(admin?m.sender_role==='admin':m.sender_role==='customer')?'mine':''}><small>{m.sender_role==='admin'?'مدیریت دلسا':'مشتری'} · {new Date(m.created_at).toLocaleString('fa-IR',{timeZone:'Asia/Tehran'})}</small>{m.body&&<p>{m.body}</p>}{m.file_path&&<Attachment message={m}/>}</article>):<div className="apu-chat-empty">فاکتور یا اولین پیامتان را ارسال کنید.</div>}</div>{error&&<p className="apu-chat-error" role="alert">{error}</p>}<form className="apu-compose" onSubmit={send}><input hidden ref={input} type="file" accept={ACCEPT} onChange={e=>select(e.target.files?.[0],kind)}/><div className="apu-upload-actions"><button type="button" disabled={busy||recording} onClick={()=>choose('invoice','.pdf,.png,.jpg,.jpeg,.webp,.xlsx,.xls,.csv')}><FileUp size={17}/>بارگذاری فاکتور</button><button type="button" disabled={busy||recording} onClick={()=>choose('attachment','.png,.jpg,.jpeg,.webp,.gif')}><ImagePlus size={17}/>عکس</button><button type="button" disabled={busy||recording} onClick={()=>choose('attachment',ACCEPT)}><FileUp size={17}/>فایل</button><button type="button" disabled={busy} onClick={()=>recording?recorder.current?.stop():startRecording()}>{recording?<Square size={17}/>:<Mic size={17}/>} {recording?'توقف ضبط · '+seconds.toLocaleString('fa-IR')+' ثانیه':'ضبط صدا'}</button></div>{file&&<div className="apu-file-preview"><span>{kind==='invoice'?'فاکتور: ':''}{file.name}</span><button type="button" disabled={busy} aria-label="برداشتن فایل انتخاب‌شده" onClick={()=>setFile(null)}><X size={17}/></button>{file.type.startsWith('audio/')&&preview&&<audio controls src={preview}/>}</div>}<textarea value={body} maxLength={4000} rows={2} onChange={e=>setBody(e.target.value)} aria-label="پیام سیستم APU" placeholder="پیام یا توضیح فاکتور…"/><div className="apu-compose-bottom"><small>حداکثر فایل: ۲۰ مگابایت · ضبط صدا: ۳ دقیقه</small><button type="submit" disabled={busy||recording||(!body.trim()&&!file)}><Send size={17}/>{busy?'در حال ارسال…':'ارسال'}</button></div></form><p className="apu-workspace-note">فایل‌ها و فاکتورها در پروندهٔ APU شما ثبت می‌شوند و مدیر می‌تواند پاسخ بدهد.</p></section>
}
