import Link from 'next/link';
import {normalizeDocument} from '../lib/site-builder';
import BuilderTemplateArt from './BuilderTemplateArt';
import styles from './SiteBuilder.module.css';
const labels={studio:'برای برندهایی که متفاوت فکر می‌کنند',catalog:'ویترین آنلاین کسب‌وکار شما',consultant:'تخصص، گفت‌وگو، راه‌حل'};
export default function BuilderSiteView({name,document,pageSlug='',base='',preview=false,onNavigate,productsSlot,shopNav,content,beforeContent,afterContent}){
 const doc=normalizeDocument(document),page=doc.pages.find(p=>p.slug===pageSlug)||doc.pages[0];
 return <div className={`${styles.website} ${styles[doc.template]||''}`} style={{'--site-accent':doc.color}}>
 <header className={styles.siteHeader}><div className={styles.siteBrand}><span className={styles.brandSymbol} aria-hidden="true">{doc.template==='studio'?'✳':doc.template==='catalog'?'◈':'◉'}</span><strong>{name}</strong></div><nav aria-label="صفحات سایت">{doc.pages.map(p=>preview?<button key={p.id} onClick={()=>onNavigate?.(p.id)} aria-current={p.slug===pageSlug?'page':undefined}>{p.title}</button>:<Link key={p.id} href={`${base}${p.slug?'/'+p.slug:''}`} aria-current={p.slug===pageSlug?'page':undefined}>{p.title}</Link>)}{shopNav}</nav></header>
 {beforeContent}<div>{content||<>{page?.blocks.map(b=><section key={b.id} id={b.type==='contact'?'contact':b.type==='products'?'products':b.type==='features'?'services':undefined} className={`${styles.siteBlock} ${styles[b.type]}`}>
 {b.type==='products'&&(productsSlot||<><div className={styles.sectionEyebrow}>ویترین کسب‌وکار</div><h2>{b.title||'محصولات فروشگاه'}</h2><p>{b.text}</p><div className={styles.emptyCatalog}><span aria-hidden="true">◈</span><strong>محصولات شما، در این ویترین</strong><p>بعد از افزودن و انتشار اولین محصول، تصویر، قیمت و گزینه‌های خرید اینجا نمایش داده می‌شوند.</p></div></>)}
 {b.type==='hero'&&<><div className={styles.heroCopy}><span className={styles.siteBadge}>{labels[doc.template]}</span><h1>{b.title}</h1><p>{b.text}</p>{b.url&&<a className={styles.siteButton} href={preview?undefined:b.url}>{b.button||'بیشتر بدانید'} <span aria-hidden="true">↗</span></a>}<div className={styles.heroSignature}><i/><span>{doc.template==='studio'?'هویت مستقل · تجربهٔ متفاوت':doc.template==='catalog'?'کشف کنید · مقایسه کنید · انتخاب کنید':'شناخت نیاز · طراحی مسیر · همراهی'}</span></div></div><div className={styles.heroVisual}>{b.image?<img src={b.image} alt={b.title} referrerPolicy="no-referrer"/>:<BuilderTemplateArt template={doc.template}/>}</div>{doc.template==='studio'&&<div className={styles.studioRibbon} aria-hidden="true"><span>ایده</span>✳<span>طراحی</span>✳<span>تجربه</span>✳<span>ارتباط</span></div>}</>}
 {b.type==='text'&&<><span className={styles.sectionEyebrow}>داستان و تخصص</span><h2>{b.title}</h2><p>{b.text}</p></>}
 {b.type==='features'&&<><div className={styles.sectionEyebrow}>{doc.template==='consultant'?'چطور همکاری می‌کنیم؟':'چه چیزی مهم است؟'}</div><h2>{b.title}</h2><p>{b.text}</p><div className={styles.featureGrid}>{b.items.map((item,i)=><article key={i}><span>{new Intl.NumberFormat('fa-IR',{minimumIntegerDigits:2}).format(i+1)}</span><h3>{item}</h3><i aria-hidden="true">↗</i></article>)}</div></>}
 {b.type==='contact'&&<><div><span className={styles.sectionEyebrow}>در ارتباط بمانیم</span><h2>{b.title}</h2><p>{b.text}</p></div>{b.url&&<a className={styles.siteButton} href={preview?undefined:b.url}>{b.button||'تماس با ما'} ↗</a>}</>}
 {b.type==='image'&&<><h2>{b.title}</h2>{b.image&&<img src={b.image} alt={b.title} loading="lazy" referrerPolicy="no-referrer"/>}<p>{b.text}</p></>}
 </section>)}{!page?.blocks.some(b=>b.type==='products')&&productsSlot}</>}{afterContent}</div>
 <footer className={styles.siteFooter}><div className={styles.siteBrand}><span className={styles.brandSymbol} aria-hidden="true">✳</span><strong>{name}</strong></div><Link href="/builder">ساخته‌شده با دلسا ↗</Link></footer></div>;
}
