'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,GripVertical,Copy,Trash2,ArrowUp,ArrowDown,Undo2,Redo2,Monitor,Smartphone,Maximize2,Minimize2,Layers,Paintbrush,Type,Image,MousePointer2,LayoutGrid,Minus,MoveVertical,Package,Mail,Upload,Search,Settings2,Save,X,CircleHelp,MessageSquareQuote,ChartNoAxesColumn,Tags,ListOrdered,UsersRound,Images,Video,Quote,ListChecks,Megaphone,Handshake,Link2,Clock,ChartNoAxesCombined,Table2} from 'lucide-react';
import {blockLabels,newBlock,uid,safeUrl,elementGroups,elementMeta} from '../lib/site-builder';
import {reorderBlock} from '../lib/builder-design';
import BuilderSiteView from './BuilderSiteView';
import BuilderElementItems from './BuilderElementItems';
import BuilderDialog from './BuilderDialog';
import ui from './BuilderVisualEditor.module.css';
const icons={hero:LayoutGrid,text:Type,features:Layers,contact:Mail,image:Image,products:Package,heading:Type,button:MousePointer2,divider:Minus,spacer:MoveVertical,faq:CircleHelp,testimonials:MessageSquareQuote,stats:ChartNoAxesColumn,pricing:Tags,steps:ListOrdered,team:UsersRound,gallery:Images,video:Video,quote:Quote,checklist:ListChecks,alert:Megaphone,logos:Handshake,links:Link2,hours:Clock,progress:ChartNoAxesCombined,table:Table2};
const descriptions={hero:'عنوان، تصویر و دعوت به اقدام',text:'معرفی و توضیحات',features:'کارت‌های ویژگی و خدمات',contact:'دعوت به تماس',image:'تصویر و توضیح',products:'محصولات منتشرشدهٔ فروشگاه',heading:'یک تیتر مستقل',button:'لینک یا تماس',divider:'تفکیک سادهٔ محتوا',spacer:'فضای تنفس بین المان‌ها'};
export default function BuilderVisualEditor({site,db,document:doc,pageId,onPage,onChange,access,busy,onSave,onPublish,allowUploads=true}){
 const page=doc.pages.find(p=>p.id===pageId)||doc.pages[0];
 const [selectedId,setSelectedId]=useState(page?.blocks[0]?.id),[panel,setPanel]=useState('add'),[device,setDevice]=useState('desktop'),[full,setFull]=useState(false),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[toolsOpen,setToolsOpen]=useState(false),[dropId,setDropId]=useState(null),[message,setMessage]=useState(''),[uploading,setUploading]=useState(false),[newPage,setNewPage]=useState(null),[history,setHistory]=useState({past:[],future:[]});
 const previousPage=useRef(page?.id),lastEdit=useRef(null),fileInput=useRef(null),historyRef=useRef(history),docRef=useRef(doc);
 historyRef.current=history;docRef.current=doc;
 const locked=!access||busy||uploading,selected=page?.blocks.find(b=>b.id===selectedId),designKey=device==='mobile'?'mobileStyle':'style',design=selected?.[designKey]||{};
 useEffect(()=>{if(previousPage.current!==page?.id){previousPage.current=page?.id;setSelectedId(page?.blocks[0]?.id);setDropId(null)}},[page?.id,page?.blocks]);
 function commit(next,group){if(locked)return;const now=Date.now(),merge=group&&lastEdit.current?.group===group&&now-lastEdit.current.time<800;setHistory(h=>({past:merge?h.past:[...h.past,doc].slice(-60),future:[]}));lastEdit.current={group,time:now};onChange(next)}
 function travel(direction){if(locked)return;const h=historyRef.current,stack=direction==='undo'?h.past:h.future;if(!stack.length)return;const next=stack[stack.length-1];setHistory(direction==='undo'?{past:h.past.slice(0,-1),future:[...h.future,docRef.current]}:{past:[...h.past,docRef.current],future:h.future.slice(0,-1)});lastEdit.current=null;onChange(next);if(!next.pages.some(p=>p.id===pageId))onPage(next.pages[0]?.id)}
 useEffect(()=>{function keyboard(e){if(e.key==='Escape')setFull(false);if(e.target.closest?.('input,textarea,select,[contenteditable=true]'))return;if((e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();travel(e.key.toLowerCase()==='y'||e.shiftKey?'redo':'undo')}}window.addEventListener('keydown',keyboard);return()=>window.removeEventListener('keydown',keyboard)},[locked,pageId]);
 function updatePage(patch,group){commit({...doc,pages:doc.pages.map(p=>p.id===page.id?{...p,...patch}:p)},group)}
 function updateBlock(patch,group){updatePage({blocks:page.blocks.map(b=>b.id===selectedId?{...b,...patch}:b)},selectedId+':'+group)}
 function styleValue(key,value){const next={...design};if(value===''||value===undefined)delete next[key];else next[key]=value;updateBlock({[designKey]:next},designKey+key)}
 function select(id){setSelectedId(id);setPanel('content');setToolsOpen(true);setMessage('')}
 function insert(type,beforeId,after=true){if(locked)return;if(page.blocks.length>=30){setMessage('حداکثر ۳۰ المان در هر صفحه قابل ثبت است.');return}const b=newBlock(type);if(type==='spacer')b.style={minHeight:48,paddingTop:0,paddingBottom:0};if(['heading','button','divider','alert','links'].includes(type))b.style={paddingTop:24,paddingBottom:24};const blocks=[...page.blocks],index=beforeId?blocks.findIndex(x=>x.id===beforeId):-1;blocks.splice(index<0?blocks.length:index+(after?1:0),0,b);updatePage({blocks});select(b.id)}
 function remove(id){if(locked||!window.confirm('این المان حذف شود؟ با «برگشت» قابل بازگردانی است.'))return;updatePage({blocks:page.blocks.filter(b=>b.id!==id)});if(selectedId===id)setSelectedId(null)}
 function duplicate(id){if(locked||page.blocks.length>=30)return;const index=page.blocks.findIndex(b=>b.id===id),b={...page.blocks[index],id:uid()},blocks=[...page.blocks];blocks.splice(index+1,0,b);updatePage({blocks});select(b.id)}
 function move(id,delta){const i=page.blocks.findIndex(b=>b.id===id),target=page.blocks[i+delta];if(!locked&&target)updatePage({blocks:reorderBlock(page.blocks,id,target.id)})}
 function drag(e,id,type){if(locked)return;e.dataTransfer.effectAllowed=type?'copy':'move';e.dataTransfer.setData(type?'application/delsa-element':'application/delsa-block',type||id)}
 function drop(e,target){e.preventDefault();e.stopPropagation();setDropId(null);if(locked)return;const type=e.dataTransfer.getData('application/delsa-element'),id=e.dataTransfer.getData('application/delsa-block');if(blockLabels[type])insert(type,target,false);else if(id){const blocks=target?reorderBlock(page.blocks,id,target):[...page.blocks.filter(b=>b.id!==id),...page.blocks.filter(b=>b.id===id)];if(blocks!==page.blocks)updatePage({blocks})}}
 async function upload(e){const file=e.target.files?.[0];e.target.value='';if(!file||locked||!selected||!allowUploads)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setMessage('تصویر JPG، PNG یا WebP تا ۵ مگابایت انتخاب کنید.');return}const id=selected.id;setUploading(true);setMessage('');try{const extension=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp',path=site.id+'/'+uid()+'.'+extension;const result=await db.storage.from('builder-product-images').upload(path,file,{contentType:file.type,upsert:false});if(result.error)throw result.error;const url=db.storage.from('builder-product-images').getPublicUrl(path).data.publicUrl;setHistory(h=>({past:[...h.past,docRef.current].slice(-60),future:[]}));onChange({...docRef.current,pages:docRef.current.pages.map(p=>({...p,blocks:p.blocks.map(b=>b.id===id?{...b,image:url}:b)}))});setMessage('تصویر در پیش‌نویس قرار گرفت.')}catch{setMessage('تصویر بارگذاری نشد. اتصال و اعتبار اشتراک را بررسی کنید.')}finally{setUploading(false)}}
 function addPage(e){e.preventDefault();const title=newPage.title.trim(),slug=newPage.slug.trim().toLowerCase();if(!title||!/^[a-z0-9-]{1,48}$/.test(slug)||['shop','product','cart','checkout','orders'].includes(slug)||doc.pages.some(p=>p.slug===slug)){setMessage('نام و آدرس معتبر و یکتا وارد کنید؛ آدرس‌های فروشگاه رزرو شده‌اند.');return}const p={id:uid(),title,slug,columns:1,gap:0,blocks:[]};commit({...doc,pages:[...doc.pages,p]});onPage(p.id);setSelectedId(null);setPanel('add');setNewPage(null)}
 useEffect(()=>{if(!toolsOpen)return;const close=e=>{if(e.key==='Escape')setToolsOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[toolsOpen]);
 function controls(b){return <div className={ui.blockTools} onClick={e=>e.stopPropagation()}><button type="button" disabled={locked} draggable={!locked} onDragStart={e=>drag(e,b.id)} aria-label={'کشیدن '+blockLabels[b.type]} title="برای جابه‌جایی بکشید"><GripVertical size={14}/>{blockLabels[b.type]}</button><button disabled={locked} aria-label="ویرایش المان" onClick={()=>select(b.id)}><Paintbrush size={14}/></button><button disabled={locked||page.blocks.length>=30} aria-label="تکثیر المان" onClick={()=>duplicate(b.id)}><Copy size={14}/></button><button disabled={locked} aria-label="حذف المان" onClick={()=>remove(b.id)}><Trash2 size={14}/></button></div>}
 function sizeField(key,label,min,max){return <label key={key}>{label}<div className={ui.numberField}><input type="number" min={min} max={max} placeholder="قالب" value={design[key]??''} onChange={e=>styleValue(key,e.target.value===''?'':Math.min(max,Math.max(min,Number(e.target.value))))}/><span>px</span></div></label>}
 return <section className={`${ui.editor} ${full?ui.fullscreen:''}`} aria-label="ویرایشگر بصری صفحات"><header className={ui.topbar}><div><strong>استودیوی طراحی</strong><small>المان را انتخاب کن، تغییر بده، نتیجه را ببین.</small></div><div className={ui.toolbar}><label className={ui.pageSelect}>صفحه<select aria-label="انتخاب صفحهٔ طراحی" value={page?.id||''} onChange={e=>onPage(e.target.value)}>{doc.pages.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><button disabled={locked||doc.pages.length>=20} onClick={()=>{setNewPage({title:'صفحهٔ جدید',slug:'page-'+uid().slice(0,8)});setMessage('')}}><Plus size={16}/>صفحه</button><button disabled={locked||!history.past.length} aria-label="برگشت تغییر" title="Ctrl+Z" onClick={()=>travel('undo')}><Undo2 size={17}/></button><button disabled={locked||!history.future.length} aria-label="جلو رفتن تغییر" onClick={()=>travel('redo')}><Redo2 size={17}/></button><button aria-label="نمای دسکتاپ" aria-pressed={device==='desktop'} onClick={()=>setDevice('desktop')}><Monitor size={17}/></button><button aria-label="نمای موبایل" aria-pressed={device==='mobile'} onClick={()=>setDevice('mobile')}><Smartphone size={17}/></button><button disabled={locked} onClick={onSave}><Save size={15}/>ذخیره</button><button disabled={locked} onClick={onPublish}>انتشار</button><button aria-label={full?'خروج از حالت تمرکز':'حالت تمرکز'} onClick={()=>setFull(v=>!v)}>{full?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</button></div></header><button className={ui.mobileToolsTrigger} aria-label="ابزارهای طراحی" aria-expanded={toolsOpen} aria-controls="builder-design-tools" onClick={()=>setToolsOpen(v=>!v)}>{toolsOpen?<X size={17}/>:<Settings2 size={17}/>}<span>{toolsOpen?'بستن ابزارها':'ابزارهای طراحی'}</span></button>{toolsOpen&&<button className={ui.toolsBackdrop} aria-label="بستن ابزارهای طراحی" onClick={()=>setToolsOpen(false)}/>} {message&&<p className={ui.notice} role="status">{message}</p>}<div className={ui.layout}><aside id="builder-design-tools" className={`${ui.inspector} ${toolsOpen?ui.toolsOpen:''}`}><div className={ui.tabs}><label>ابزارهای طراحی<select aria-label="بخش ابزارهای طراحی" value={panel} onChange={e=>setPanel(e.target.value)}>{[['add','المان‌ها'],['content','محتوا'],['style','طراحی'],['layers','لایه‌ها'],['page','صفحه']].map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label></div><fieldset disabled={locked} className={ui.fields}>
 {panel==='add'&&<><h3>چه چیزی اضافه کنیم؟</h3><p>روی المان بزن یا آن را روی بوم بکش. المان تازه بعد از انتخاب فعلی قرار می‌گیرد.</p><label className={ui.search}><Search size={15}/><input aria-label="جست‌وجوی المان" placeholder="متن، تصویر، دکمه…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>دستهٔ المان‌ها<select aria-label="دستهٔ المان‌ها" value={category} onChange={e=>setCategory(e.target.value)}><option value="">همهٔ المان‌ها · ۲۶ مورد</option>{Object.entries(elementGroups).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className={ui.palette}>{Object.entries(blockLabels).filter(([key,label])=>(!category||elementMeta[key]?.group===category)&&(label+' '+(elementMeta[key]?.description||descriptions[key]||'')).includes(search)).map(([type,label])=>{const Icon=icons[type]||LayoutGrid;return <button key={type} draggable={!locked} onDragStart={e=>drag(e,null,type)} onClick={()=>insert(type,selectedId)}><Icon size={23}/><strong>{label}</strong><small>{elementMeta[type]?.description||descriptions[type]}</small></button>})}</div><h3>چیدمان سریع</h3><div className={ui.presets}>{[1,2,3,4].map(n=><button key={n} onClick={()=>{updatePage({columns:n,gap:n===1?0:16});setPanel('page')}}><LayoutGrid size={16}/>{n.toLocaleString('fa-IR')} ستون</button>)}</div><p>المان‌های قبلی تمام‌عرض می‌مانند؛ عرض هر المان را از «طراحی» مشخص کن.</p></>}
 {['content','style'].includes(panel)&&!selected&&<div className={ui.empty}><MousePointer2 size={30}/><strong>یک المان را انتخاب کن</strong><p>روی بخش دلخواه در بوم بزن یا از «لایه‌ها» انتخاب کن.</p><button onClick={()=>setPanel('add')}><Plus size={15}/>افزودن المان</button></div>}
 {panel==='content'&&selected&&<><div className={ui.inspectorHeading}><strong>{blockLabels[selected.type]}</strong><button onClick={()=>setPanel('style')}><Paintbrush size={15}/>ظاهر</button></div>{!['divider','spacer','button'].includes(selected.type)&&<label>عنوان<input maxLength={180} value={selected.title} onChange={e=>updateBlock({title:e.target.value},'title')}/></label>}{!['divider','spacer','button','heading'].includes(selected.type)&&<label>توضیحات<textarea rows={4} maxLength={4000} value={selected.text} onChange={e=>updateBlock({text:e.target.value},'text')}/></label>}{['hero','contact','button','alert','pricing','video'].includes(selected.type)&&<>{selected.type!=='video'&&<label>متن دکمه<input maxLength={80} value={selected.button} onChange={e=>updateBlock({button:e.target.value},'button')}/></label>}<label>{selected.type==='video'?'لینک مستقیم ویدیو':'مقصد دکمه'}<input dir="ltr" maxLength={2048} placeholder="https://example.com یا #contact" value={selected.url} onChange={e=>updateBlock({url:e.target.value},'url')}/></label>{selected.url&&!safeUrl(selected.url)&&<p role="alert">لینک باید با https://، /، #، tel: یا mailto: شروع شود.</p>}</>}{(elementMeta[selected.type]?.items||selected.type==='features')&&<><h3>موارد این المان</h3><BuilderElementItems type={selected.type} items={selected.items} onChange={items=>updateBlock({items},'items')}/>{selected.type==='table'&&<label>ردیف‌های جدول<textarea rows={6} value={selected.items.join('\n')} placeholder={elementMeta.table.hint} onChange={e=>updateBlock({items:e.target.value.split('\n').slice(0,12)},'items')}/><small>{elementMeta.table.hint}</small></label>}</>}{selected.type==='video'&&<p>{elementMeta.video.hint}</p>}{['hero','image','video'].includes(selected.type)&&<><label>تصویر<input ref={fileInput} type="file" disabled={!allowUploads} accept="image/jpeg,image/png,image/webp" onChange={upload}/></label><small>{allowUploads?'از دستگاه انتخاب کن؛ تا ۵ مگابایت.':'برای بارگذاری فایل وارد پنل خودت شو؛ در نمونه می‌توانی لینک تصویر وارد کنی.'}</small><label>یا لینک HTTPS تصویر<input dir="ltr" type="url" maxLength={2048} value={selected.image} onChange={e=>updateBlock({image:e.target.value},'image')}/></label>{selected.image&&<><img className={ui.imageThumb} src={selected.image} alt="پیش‌نمایش تصویر" referrerPolicy="no-referrer"/><button onClick={()=>updateBlock({image:''},'image')}>حذف تصویر از المان</button></>}</>}{selected.type==='products'&&<p>محصولات واقعی از بخش «محصولات» فروشگاه خوانده می‌شوند. عنوان و طراحی ویترین را اینجا تنظیم کن.</p>}<div className={ui.rowActions}><button onClick={()=>duplicate(selected.id)} disabled={page.blocks.length>=30}><Copy size={15}/>تکثیر</button><button onClick={()=>remove(selected.id)}><Trash2 size={15}/>حذف</button></div></>}
 {panel==='style'&&selected&&<><h3>طراحی {blockLabels[selected.type]}</h3><div className={ui.deviceNote}>{device==='mobile'?'تنظیمات اختصاصی موبایل؛ فیلد خالی از دسکتاپ پیروی می‌کند.':'تنظیمات دسکتاپ و پایهٔ موبایل'}</div><label>تراز محتوا<select value={design.align||''} onChange={e=>styleValue('align',e.target.value)}><option value="">پیش‌فرض قالب</option><option value="right">راست</option><option value="center">وسط</option><option value="left">چپ</option></select></label>{device==='desktop'&&<label>عرض در چیدمان {page.columns||1} ستونه<select value={design.span||''} onChange={e=>styleValue('span',e.target.value===''?'':Number(e.target.value))}><option value="">تمام عرض</option>{Array.from({length:page.columns||1},(_,i)=><option key={i} value={i+1}>{i+1} ستون</option>)}</select></label>}{['background','textColor'].map((key,i)=><label key={key}>{i?'رنگ نوشته':'رنگ پس‌زمینه'}<div className={ui.colorField}><input type="color" aria-label={i?'انتخاب رنگ نوشته':'انتخاب رنگ پس‌زمینه'} value={design[key]|| (i?'#222222':'#ffffff')} onChange={e=>styleValue(key,e.target.value)}/><span dir="ltr">{design[key]||'قالب'}</span><button aria-label="بازنشانی رنگ" onClick={()=>styleValue(key,undefined)}><Undo2 size={14}/></button></div></label>)}<div className={ui.twoFields}>{sizeField('titleSize','اندازهٔ عنوان',16,100)}{sizeField('bodySize','اندازهٔ متن',10,32)}{sizeField('paddingTop','فاصلهٔ بالا',0,240)}{sizeField('paddingBottom','فاصلهٔ پایین',0,240)}{sizeField('paddingX','فاصلهٔ دو طرف',0,160)}{sizeField('radius','گردی گوشه‌ها',0,80)}{sizeField('minHeight','حداقل ارتفاع',0,800)}{sizeField('maxWidth','حداکثر عرض',280,1800)}</div>{selected.type==='features'&&<label>تعداد ستون کارت‌ها<select value={design.featureColumns||''} onChange={e=>styleValue('featureColumns',e.target.value===''?'':Number(e.target.value))}><option value="">قالب</option>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label>}<label className={ui.check}><input type="checkbox" checked={Boolean(selected.style?.[device==='mobile'?'hiddenMobile':'hiddenDesktop'])} onChange={e=>updateBlock({style:{...selected.style,[device==='mobile'?'hiddenMobile':'hiddenDesktop']:e.target.checked}},'visibility')}/>پنهان در {device==='mobile'?'موبایل':'دسکتاپ'}</label><button onClick={()=>updateBlock({[designKey]:{}},'reset')}>بازنشانی طراحی {device==='mobile'?'موبایل':'دسکتاپ'}</button></>}
 {panel==='layers'&&<><h3>ساختار صفحه</h3><p>با دستگیره بکش یا با فلش‌ها جابه‌جا کن.</p><div className={ui.layerList}>{page.blocks.map((b,i)=><div className={selectedId===b.id?ui.activeLayer:''} key={b.id} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,b.id)}><button draggable={!locked} onDragStart={e=>drag(e,b.id)} onClick={()=>select(b.id)}><GripVertical size={15}/><span>{b.title||blockLabels[b.type]}<small>{blockLabels[b.type]}</small></span></button><button disabled={!i} aria-label="المان به بالا" onClick={()=>move(b.id,-1)}><ArrowUp size={13}/></button><button disabled={i===page.blocks.length-1} aria-label="المان به پایین" onClick={()=>move(b.id,1)}><ArrowDown size={13}/></button></div>)}</div><button onClick={()=>setPanel('add')}><Plus size={16}/>افزودن المان</button></>}
 {panel==='page'&&<><h3>تنظیمات صفحه</h3><label>نام صفحه<input maxLength={120} value={page.title} onChange={e=>updatePage({title:e.target.value},'page-title')}/></label>{page.slug!==''&&<label>آدرس صفحه<input dir="ltr" maxLength={48} value={page.slug} onChange={e=>{const slug=e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'');if(slug&&!['shop','product','cart','checkout','orders'].includes(slug)&&!doc.pages.some(p=>p.id!==page.id&&p.slug===slug))updatePage({slug},'page-slug')}}/></label>}<label>ستون‌های بوم<select value={page.columns||1} onChange={e=>updatePage({columns:Number(e.target.value)},'columns')}>{[1,2,3,4].map(n=><option key={n} value={n}>{n} ستون</option>)}</select></label><label>فاصلهٔ بین المان‌ها<input type="range" min="0" max="80" value={page.gap||0} onChange={e=>updatePage({gap:Number(e.target.value)},'gap')}/><small>{page.gap||0} px</small></label><p>موبایل خودکار تک‌ستونه می‌شود. ظاهر اختصاصی موبایل را از نمای موبایل تنظیم کن.</p>{page.slug!==''&&<button onClick={()=>{if(!window.confirm('این صفحه حذف شود؟ با «برگشت» قابل بازیابی است.'))return;commit({...doc,pages:doc.pages.filter(p=>p.id!==page.id)});onPage(doc.pages[0].id)}}><Trash2 size={15}/>حذف صفحه</button>}</>}
 </fieldset></aside><div className={ui.canvasArea}><div className={ui.canvasCaption}><span><i/> پیش‌نمایش زندهٔ پیش‌نویس</span><small>{device==='mobile'?'۳۹۰ پیکسل · موبایل':'دسکتاپ · متناسب با بوم'}</small></div><div className={`${ui.canvas} ${device==='mobile'?ui.mobile:''}`}><BuilderSiteView name={site.name} document={doc} pageSlug={page?.slug} preview onNavigate={onPage} editor={{selectedId,dropId,onSelect:select,onDragOver:setDropId,onDrop:drop,controls}}/><div className={ui.addZone} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,null)}><button disabled={locked||page.blocks.length>=30} onClick={()=>{setSelectedId(null);setPanel('add');setToolsOpen(true)}}><Plus size={20}/>افزودن المان به صفحه</button><span>یا یک المان را از پنل اینجا رها کن.</span></div></div><p className={ui.bottomHint}>با «ذخیره» پیش‌نویس نگه داشته می‌شود؛ «انتشار سایت» تغییرات را عمومی می‌کند.</p></div></div>{newPage&&<BuilderDialog title="افزودن صفحه" onClose={()=>setNewPage(null)}><form className={ui.pageForm} onSubmit={addPage}><label>نام صفحه<input required maxLength={120} value={newPage.title} onChange={e=>setNewPage({...newPage,title:e.target.value})}/></label><label>آدرس صفحه<input required dir="ltr" maxLength={48} pattern="[a-z0-9-]+" value={newPage.slug} onChange={e=>setNewPage({...newPage,slug:e.target.value})}/></label>{message&&<p role="alert">{message}</p>}<button disabled={locked} type="submit"><Plus size={16}/>ساخت صفحهٔ خالی</button></form></BuilderDialog>}</section>;
}
