'use client';
import {useEffect,useState} from 'react';
const plans={demo:'دمو (۷ روز)',month:'۱ ماهه',quarter:'۳ ماهه',year:'۱ ساله'};
export default function CustomerDetails({customer,products,onChanged}){
 const [data,setData]=useState(null),[store,setStore]=useState({name:'',website:''}),[productId,setProductId]=useState(''),[plan,setPlan]=useState('month'),[secrets,setSecrets]=useState({}),[editing,setEditing]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/customer-details?customerId='+encodeURIComponent(customer.id),{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(v.error);setData(v);setStore(v.store||{name:'',website:''});}
 useEffect(()=>{load().catch(e=>setError(e.message));},[customer.id]);
 async function action(payload){setBusy(true);setError('');try{const r=await fetch('/api/admin/customer-details',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:customer.id,...payload})}),v=await r.json();if(!r.ok)throw Error(v.error);await load();if(payload.action==='role'||payload.action==='delete-customer')onChanged?.();}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function removeSubscription(id){if(!confirm('اشتراک حذف شود؟'))return;setBusy(true);try{const r=await fetch('/api/admin/customer-details?customerId='+customer.id+'&id='+id,{method:'DELETE'}),v=await r.json();if(!r.ok)throw Error(v.error);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function reveal(id){if(secrets[id]){setSecrets(s=>({...s,[id]:null}));return}try{const r=await fetch('/api/admin/platform-credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reveal',id})}),v=await r.json();if(!r.ok)throw Error(v.error);setSecrets(s=>({...s,[id]:v.password}))}catch(e){setError(e.message)}}
 async function removeCredential(id){if(!confirm('این دسترسی حذف شود؟'))return;const r=await fetch('/api/admin/platform-credentials?id='+id,{method:'DELETE'});if(r.ok){setSecrets(s=>({...s,[id]:null}));load().catch(e=>setError(e.message))}else setError((await r.json()).error)}
 async function updateCredential(e){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/admin/platform-credentials',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...editing,customerId:customer.id})}),v=await r.json();if(!r.ok)throw Error(v.error);setEditing(null);setSecrets({});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const days=date=>Math.max(0,Math.ceil((new Date(date).getTime()-Date.now())/86400000));
 return <div className="customer-detail" onClick={e=>e.stopPropagation()}>
  {error&&<p className="admin-form-error" role="alert">{error}</p>}
  <label>نقش <select value={customer.role} disabled={busy} onChange={e=>action({action:'role',role:e.target.value})}><option value="user">کاربر</option><option value="admin">مدیر</option></select></label>
  <h3>اکانت‌های فعال</h3>
  <div className="detail-inline"><select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">انتخاب محصول فروشگاه</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={plan} onChange={e=>setPlan(e.target.value)}>{Object.entries(plans).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button disabled={busy||!productId} onClick={()=>action({action:'subscription',productId,plan})}>ثبت / تمدید</button></div>
  {!data?<p>در حال بارگذاری…</p>:<>
   {data.subscriptions.map(s=><div className="detail-line" key={s.id}><b>{products.find(p=>p.id===s.product_id)?.name||'محصول حذف‌شده'}</b><span>{plans[s.plan]} · {days(s.expires_at)} روز باقی‌مانده</span><button disabled={busy} aria-label="یک روز اضافه" onClick={()=>action({action:'adjust',subscriptionId:s.id,days:1})}>+</button><button disabled={busy} aria-label="یک روز کم" onClick={()=>action({action:'adjust',subscriptionId:s.id,days:-1})}>−</button><button disabled={busy} onClick={()=>removeSubscription(s.id)}>حذف</button></div>)}
   <h3>فروشگاه</h3><div className="detail-inline"><input value={store.name||''} maxLength={120} placeholder="اسم فروشگاه" onChange={e=>setStore({...store,name:e.target.value})}/><input value={store.website||''} type="url" dir="ltr" placeholder="https://example.com" onChange={e=>setStore({...store,website:e.target.value})}/><button disabled={busy} onClick={()=>action({action:'store',...store})}>ذخیره تغییرات</button></div>
   <h3>دسترسی‌های مشتری</h3>{data.credentials.length?data.credentials.map(c=><div className="detail-line" key={c.id}><b>{c.platform}</b><span dir="ltr">{c.username}</span><code dir="ltr">{secrets[c.id]||'••••••••'}</code><button onClick={()=>reveal(c.id)}>{secrets[c.id]?'پنهان':'نمایش'}</button><button disabled={!secrets[c.id]} onClick={()=>navigator.clipboard.writeText(secrets[c.id])}>کپی</button><button onClick={()=>setEditing({id:c.id,platform:c.platform,username:c.username,password:''})}>ویرایش</button><button onClick={()=>removeCredential(c.id)}>حذف</button></div>):<p>دسترسی ثبت نشده است. از بلوک اطلاعات مشتری اضافه کنید.</p>}
   {editing&&<form className="detail-inline" onSubmit={updateCredential}><input aria-label="نام پلتفرم" required value={editing.platform} onChange={e=>setEditing({...editing,platform:e.target.value})}/><input aria-label="یوزرنیم" required value={editing.username} onChange={e=>setEditing({...editing,username:e.target.value})}/><input aria-label="رمز جدید" type="password" autoComplete="new-password" placeholder="رمز جدید (اختیاری)" value={editing.password} onChange={e=>setEditing({...editing,password:e.target.value})}/><button disabled={busy}>ذخیره</button><button type="button" onClick={()=>setEditing(null)}>انصراف</button></form>}
  </>}
  <button className="detail-danger" disabled={busy} onClick={()=>{if(confirm('حساب و همه اطلاعات این مشتری برای همیشه حذف شود؟'))action({action:'delete-customer'})}}>حذف مشتری</button>
 </div>;
}
