'use client';
import {useEffect,useState} from 'react';
import CustomerApuDetails from './CustomerApuDetails';
import {daysRemainingIran} from '../lib/subscription-days';

const plans={demo:'دمو (۷ روز)',month:'۱ ماهه',quarter:'۳ ماهه',year:'۱ ساله'};
const emptyAccess={platform:'',username:'',password:''};

export default function CustomerDetails({customer,products,onChanged,onSubscriptionsChanged}){
 const [data,setData]=useState(null),[store,setStore]=useState({name:'',website:''}),[productId,setProductId]=useState(''),[plan,setPlan]=useState('month');
 const [secrets,setSecrets]=useState({}),[editing,setEditing]=useState(null),[adding,setAdding]=useState(false),[access,setAccess]=useState(emptyAccess);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[clock,setClock]=useState(null);
 async function load(){const r=await fetch('/api/admin/customer-details?customerId='+encodeURIComponent(customer.id),{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(v.error);setData(v);setStore(v.store||{name:'',website:''});onSubscriptionsChanged?.(v.subscriptions||[]);}
 useEffect(()=>{load().catch(e=>setError(e.message));setClock(Date.now());const timer=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(timer)},[customer.id]);
 async function action(payload){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/customer-details',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:customer.id,...payload})}),v=await r.json();if(!r.ok)throw Error(v.error);if(payload.action==='delete-customer'){onChanged?.();return}await load();if(payload.action==='role')onChanged?.()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function removeSubscription(id){if(!confirm('اشتراک حذف شود؟'))return;setBusy(true);setError('');try{const r=await fetch('/api/admin/customer-details?customerId='+encodeURIComponent(customer.id)+'&id='+encodeURIComponent(id),{method:'DELETE'}),v=await r.json();if(!r.ok)throw Error(v.error);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function passwordFor(id){const r=await fetch('/api/admin/platform-credentials',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({action:'reveal',id})}),v=await r.json();if(!r.ok)throw Error(v.error);return v.password}
 async function reveal(id){if(secrets[id]){setSecrets(s=>({...s,[id]:null}));return}try{setError('');const password=await passwordFor(id);setSecrets(s=>({...s,[id]:password}))}catch(e){setError(e.message)}}
 async function copyPassword(id){try{setError('');const password=await passwordFor(id);await navigator.clipboard.writeText(password);setNotice('رمز عبور کپی شد.')}catch(e){setError(e.message||'کپی رمز عبور انجام نشد.')}}
 async function removeCredential(id){if(!confirm('این دسترسی حذف شود؟'))return;setBusy(true);setError('');try{const r=await fetch('/api/admin/platform-credentials?id='+encodeURIComponent(id),{method:'DELETE'}),v=await r.json();if(!r.ok)throw Error(v.error);setSecrets(s=>({...s,[id]:null}));await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function saveCredential(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const updating=Boolean(editing);const r=await fetch('/api/admin/platform-credentials',{method:updating?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...updating?editing:access,customerId:customer.id})}),v=await r.json();if(!r.ok)throw Error(v.error);setEditing(null);setAdding(false);setAccess(emptyAccess);setSecrets({});await load();setNotice(updating?'دسترسی به‌روزرسانی شد.':'دسترسی اضافه شد.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const form=editing||access,setForm=editing?setEditing:setAccess;
 return <div className="customer-detail" onClick={e=>e.stopPropagation()}>
  {error&&<p className="admin-form-error" role="alert">{error}</p>}{notice&&<p className="admin-form-success" role="status">{notice}</p>}
  <label>نقش <select value={customer.role} disabled={busy} onChange={e=>action({action:'role',role:e.target.value})}><option value="user">کاربر</option><option value="admin">مدیر</option></select></label>
  <h3>اکانت‌های فعال</h3>
  <div className="detail-inline"><select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">انتخاب محصول فروشگاه</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={plan} onChange={e=>setPlan(e.target.value)}>{Object.entries(plans).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button disabled={busy||!productId} onClick={()=>action({action:'subscription',productId,plan})}>ثبت / تمدید</button></div>
  {!data?<p>در حال بارگذاری…</p>:<>
   {data.subscriptions.length===0&&<p className="detail-empty">اشتراکی ثبت نشده است.</p>}
   {data.subscriptions.map(s=><div className="detail-line detail-subscription" key={s.id}><b>{products.find(p=>p.id===s.product_id)?.name||'محصول حذف‌شده'}</b><span>{plans[s.plan]}</span><span className="subscription-days">{daysRemainingIran(s.expires_at,clock||Date.now()).toLocaleString('fa-IR')} روز باقی‌مانده</span><div className="detail-actions"><button disabled={busy} aria-label="یک روز اضافه" onClick={()=>action({action:'adjust',subscriptionId:s.id,days:1})}>+</button><button disabled={busy} aria-label="یک روز کم" onClick={()=>action({action:'adjust',subscriptionId:s.id,days:-1})}>−</button><button disabled={busy} onClick={()=>removeSubscription(s.id)}>حذف</button></div></div>)}
   <h3>فروشگاه</h3><div className="detail-inline"><input value={store.name||''} maxLength={120} placeholder="اسم فروشگاه" onChange={e=>setStore({...store,name:e.target.value})}/><input value={store.website||''} type="url" dir="ltr" placeholder="https://example.com" onChange={e=>setStore({...store,website:e.target.value})}/><button disabled={busy} onClick={()=>action({action:'store',...store})}>ذخیره تغییرات</button></div>
   <div className="detail-heading"><h3>دسترسی‌های مشتری</h3><button type="button" disabled={busy} onClick={()=>{setEditing(null);setAccess(emptyAccess);setAdding(v=>!v)}}>{adding?'بستن فرم':'افزودن دسترسی +'}</button></div>
   {data.credentials.length?data.credentials.map(c=><div className="detail-line detail-credential" key={c.id}><b>{c.platform}</b><span dir="ltr">{c.username}</span><code dir="ltr">{secrets[c.id]||'••••••••'}</code><div className="detail-actions"><button onClick={()=>reveal(c.id)}>{secrets[c.id]?'پنهان':'نمایش'}</button><button onClick={()=>copyPassword(c.id)}>کپی رمز</button><button onClick={()=>{setAdding(false);setEditing({id:c.id,platform:c.platform,username:c.username,password:''})}}>ویرایش</button><button disabled={busy} onClick={()=>removeCredential(c.id)}>حذف</button></div></div>):<p className="detail-empty">هنوز دسترسی ثبت نشده است.</p>}
   {(adding||editing)&&<form className="detail-access-form" onSubmit={saveCredential}><label>نام پلتفرم<input required maxLength={80} value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})} placeholder="مثلاً ترب"/></label><label>یوزرنیم<input required maxLength={255} dir="ltr" value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="نام کاربری"/></label><label>{editing?'رمز جدید (اختیاری)':'پسورد'}<input required={!editing} maxLength={500} type="password" autoComplete="new-password" dir="ltr" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="رمز عبور"/></label><div className="detail-form-actions"><button disabled={busy} type="submit">{editing?'ذخیره تغییرات':'افزودن دسترسی'}</button><button type="button" onClick={()=>{setEditing(null);setAdding(false)}}>انصراف</button></div></form>}
  </>}
  <CustomerApuDetails customerId={customer.id}/>
  <button className="detail-danger" disabled={busy} onClick={()=>{if(confirm('حساب و همه اطلاعات این مشتری برای همیشه حذف شود؟'))action({action:'delete-customer'})}}>حذف مشتری</button>
 </div>;
}
