'use client';
import {useEffect,useState} from 'react';
import {WalletCards,PanelsTopLeft,RefreshCw,FileText} from 'lucide-react';
const number=n=>Number(n||0).toLocaleString('fa-IR');
const time=d=>new Date(d).toLocaleString('fa-IR',{timeZone:'Asia/Tehran'});
const eventNames={'product.saved':'ذخیرهٔ محصول','variant.updated':'تغییر قیمت یا موجودی','order.created':'ثبت سفارش','order.updated':'تغییر وضعیت سفارش','site.archived':'بایگانی سایت','site.restored':'بازگردانی سایت'};
export default function CustomerServiceOverview({mode,subscriptions,hasApu,runs,sources,rules,db,userId,onOpen}){
 const [sites,setSites]=useState([]),[events,setEvents]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('all');
 useEffect(()=>{let alive=true,pending=false;async function load(){if(pending||document.visibilityState==='hidden')return;pending=true;try{const s=await db.from('builder_sites').select('id,name').eq('owner_id',userId).is('deleted_at',null).order('created_at',{ascending:false}).limit(100);if(s.error)throw s.error;const ids=(s.data||[]).map(x=>x.id);const e=ids.length?await db.from('builder_events').select('id,site_id,kind,created_at').in('site_id',ids).order('id',{ascending:false}).limit(50):{data:[]};if(e.error)throw e.error;if(alive){setSites(s.data||[]);setEvents(e.data||[]);setError('')}}catch{if(alive)setError('فعالیت سایت‌ها بارگذاری نشد. دوباره تلاش کنید.')}finally{pending=false;if(alive)setLoading(false)}}load();const timer=setInterval(load,60000);window.addEventListener('focus',load);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',load)}},[db,userId]);
 const hasBuilder=subscriptions.some(s=>s.store_products?.service_code==='site_builder');
 const services=[...new Map(subscriptions.map(s=>[s.product_id,{id:s.product_id,name:s.store_products?.name||'محصول',code:s.store_products?.service_code}])).values()];
 const reports=[...(hasApu?runs.map(r=>({id:'apu-'+r.id,service:'apu',title:'اجرای APU',date:r.created_at,detail:`${r.status==='completed'?'موفق':r.status==='partial'?'ناقص':'ناموفق'} · ${number(r.updated_count)} به‌روزرسانی · ${number(r.failed_count)} خطا`,summary:r.summary})):[]),...events.map(e=>({id:'builder-'+e.id,service:'site_builder',title:eventNames[e.kind]||'فعالیت فروشگاه',date:e.created_at,detail:sites.find(s=>s.id===e.site_id)?.name||'سایت'}))].sort((a,b)=>new Date(b.date)-new Date(a.date));
 const visible=reports.filter(r=>filter==='all'||r.service===filter);
 if(mode==='reports')return <section className="customer-panel"><div className="customer-panel-title"><h2>گزارش‌ها و اجراها</h2><select className="customer-report-filter" value={filter} onChange={e=>setFilter(e.target.value)} aria-label="سرویس گزارش"><option value="all">همهٔ سرویس‌ها</option>{hasApu&&<option value="apu">سیستم APU</option>}{(hasBuilder||sites.length>0)&&<option value="site_builder">سایت‌ساز دلسا</option>}</select></div>{error&&<p role="alert">{error}</p>}{loading?<p role="status">در حال بارگذاری فعالیت‌ها…</p>:visible.length?<div className="customer-service-reports">{visible.map(r=><article key={r.id}><FileText size={18}/><div><strong>{r.title}</strong><p>{r.service==='apu'?'APU':'سایت‌ساز'} · {r.detail}</p>{r.summary&&<p>{r.summary}</p>}</div><time>{time(r.date)}</time></article>)}</div>:<div className="customer-empty"><FileText size={28}/><strong>هنوز فعالیتی ثبت نشده</strong><p>گزارش هر سرویس پس از انجام فعالیت واقعی نمایش داده می‌شود.</p></div>}</section>;
 return <><section className="customer-hero"><div className="customer-hero-icon"><WalletCards size={24}/></div><div><span>DELSA WORKSPACE</span><h2>فضای کاری سرویس‌های تو</h2><p>{services.length?services.map(s=>s.name).join(' · '):'هنوز اشتراک فعالی نداری. اشتراک‌های ثبت‌شده توسط مدیر اینجا نمایش داده می‌شوند.'}</p></div></section><div className="customer-stats"><article><WalletCards/><span>اشتراک‌های فعال</span><strong>{number(subscriptions.length)}</strong></article>{hasBuilder&&<article><PanelsTopLeft/><span>سایت‌های من</span><strong>{loading?'…':number(sites.length)}</strong></article>}{hasApu&&<><article><RefreshCw/><span>منابع فعال APU</span><strong>{number(sources.filter(s=>s.enabled).length)}</strong><small>{number(rules.filter(r=>r.enabled).length)} قانون فعال</small></article><article><FileText/><span>اجراهای APU</span><strong>{number(runs.length)}</strong><small>تا ۲۰ اجرای اخیر</small></article></>}</div><div className="customer-service-grid">{services.map(service=><section className="customer-panel" key={service.id}><div className="customer-panel-title"><h2>{service.name}</h2><span className="customer-count">اشتراک فعال</span></div>{service.code==='site_builder'?<><p>سایت، محصولات، سفارش‌ها و مشتریان فروشگاهت را مدیریت کن.</p><button className="customer-primary" onClick={()=>onOpen('builder')}>ورود به سایت‌ساز</button></>:service.code==='apu'?<><p>فاکتور، منابع قیمت و قانون‌های اختصاصی APU را آماده کن.</p><div className="customer-quick-actions"><button onClick={()=>onOpen('apu')}>فاکتورها و گفت‌وگو</button><button onClick={()=>onOpen('sources')}>منابع قیمت</button><button onClick={()=>onOpen('rules')}>قوانین</button></div></>:<><p>اطلاعات اشتراک و هماهنگی سرویس در حساب شما در دسترس است.</p><button className="customer-primary" onClick={()=>onOpen('account')}>جزئیات اشتراک</button></>}</section>)}<section className="customer-panel"><h2>فعالیت و ارتباط</h2>{error&&<p role="alert">{error}</p>}<p>{reports[0]?reports[0].title+' · '+time(reports[0].date):'هنوز فعالیتی از سرویس‌های شما ثبت نشده است.'}</p><div className="customer-quick-actions"><button onClick={()=>onOpen('reports')}>همهٔ گزارش‌ها</button><button onClick={()=>onOpen('support')}>پشتیبانی</button></div></section></div></>;
}
