'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import {MessageCircle,Send,X} from 'lucide-react';
import {createClient} from '../lib/supabase/client';
import ChatMessage from './ChatMessage';
const TOKEN_KEY='delsa-visitor-chat-token';
export default function VisitorChat(){
 const pathname=usePathname(),hidden=pathname?.startsWith('/admin'),stream=useRef(null),pinned=useRef(true);
 const [open,setOpen]=useState(false),[chat,setChat]=useState(null),[body,setBody]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const refresh=useCallback(async()=>{const token=localStorage.getItem(TOKEN_KEY);if(!token)return;const {data,error}=await createClient().rpc('visitor_chat_read',{p_token:token});if(!error)setChat(data);},[]);
 useEffect(()=>{if(hidden)return;refresh();const show=()=>setOpen(true);window.addEventListener('delsa:open-chat',show);const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh()},5000);return()=>{window.removeEventListener('delsa:open-chat',show);clearInterval(timer)}},[refresh,hidden]);
 useEffect(()=>{if(open&&pinned.current&&stream.current)stream.current.scrollTop=stream.current.scrollHeight},[open,chat?.chat_id,chat?.messages?.length,chat?.full_name]);
 async function send(event){event.preventDefault();if(busy||!body.trim())return;setBusy(true);setError('');try{const db=createClient(),token=localStorage.getItem(TOKEN_KEY);const result=token?await db.rpc('visitor_chat_send',{p_token:token,p_body:body.trim()}):await db.rpc('visitor_chat_start',{p_body:body.trim()});if(result.error)throw result.error;if(!token)localStorage.setItem(TOKEN_KEY,result.data.token);setChat(result.data);setBody('')}catch(err){setError(err.message?.includes('wait')?'لطفاً چند لحظه دیگر دوباره تلاش کنید.':'ارسال انجام نشد. دوباره تلاش کنید.')}finally{setBusy(false)}}
 async function identify(event){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const {data,error}=await createClient().rpc('visitor_chat_identify',{p_token:localStorage.getItem(TOKEN_KEY),p_name:name.trim(),p_phone:phone.trim()});if(error)throw error;setChat(data);setName('');setPhone('')}catch{setError('نام و نام خانوادگی کامل و شماره تماس معتبر وارد کنید.')}finally{setBusy(false)}}
 async function messageAction(item,action,value){const {data,error}=await createClient().rpc('visitor_message_action',{p_token:localStorage.getItem(TOKEN_KEY),p_id:item.id,p_action:action,p_body:value});if(error)throw error;setChat(data)}
 if(hidden)return null;
 return <div className="visitor-chat-root"><button className="visitor-chat-launch" onClick={()=>setOpen(v=>!v)} aria-label="پشتیبانی آنلاین" aria-expanded={open}><MessageCircle size={22}/><span>پشتیبانی آنلاین</span></button>{open&&<section className="visitor-chat-popup" role="dialog" aria-label="چت با پشتیبانی دلسا"><header><div><strong>گفت‌وگو با دلسا</strong><small>پیام شما در پنل پشتیبانی ثبت می‌شود</small></div><button onClick={()=>setOpen(false)} aria-label="بستن چت"><X size={19}/></button></header><div className="visitor-chat-stream" ref={stream} onScroll={e=>{const el=e.currentTarget;pinned.current=el.scrollHeight-el.clientHeight-el.scrollTop<60}} aria-live="polite"><p className="visitor-chat-intro">سلام! پرسشتان را بنویسید تا از همین‌جا پاسخ بگیرید.</p>{chat?.messages?.map(item=><div key={item.id} className={'visitor-bubble '+(item.sender_role==='visitor'?'mine':'')}><small>{item.sender_role==='visitor'?'شما':item.sender_role==='admin'?'پشتیبانی دلسا':'دلسا'}</small><ChatMessage message={item} canEdit={item.sender_role==='visitor'} canDeleteAll={item.sender_role==='visitor'} maxLength={2000} onAction={(action,value)=>messageAction(item,action,value)}/></div>)}{chat&&!chat.full_name&&<form className="visitor-identity-form" onSubmit={identify}><strong>اطلاعات تماس شما</strong><p>برای پیگیری گفت‌وگو، این فرم را تکمیل کنید.</p><label htmlFor="visitor-name">نام و نام خانوادگی</label><input id="visitor-name" required minLength={2} maxLength={120} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="نام و نام خانوادگی کامل"/><label htmlFor="visitor-phone">شماره تماس</label><input id="visitor-phone" required type="tel" inputMode="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="۰۹۱۲۳۴۵۶۷۸۹" dir="ltr"/><button disabled={busy||!name.trim()||!phone.trim()} type="submit">{busy?'در حال ثبت…':'ثبت اطلاعات'}</button></form>}</div>{error&&<p className="visitor-chat-error" role="alert">{error}</p>}<form className="visitor-chat-compose" onSubmit={send}><textarea required maxLength={2000} rows={2} value={body} onChange={e=>setBody(e.target.value)} placeholder="پیام خود را بنویسید…" aria-label="پیام"/><button disabled={busy||!body.trim()}><Send size={17}/>{busy?'در حال ارسال…':'ارسال'}</button></form></section>}</div>;
}
