'use client';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useState} from 'react';
import {LayoutDashboard, RefreshCw, MessagesSquare, SlidersHorizontal, ArrowUpLeft, ArrowLeft, Search, Download, Check, Clock, Link2, Menu, X, Shield, Store, Package, CircleHelp} from 'lucide-react';
const initial=[{id:1,name:'کتاب هنر شفاف اندیشیدن',sku:'BK-101',price:240000,next:255000,stock:12,status:'review'},{id:2,name:'کتاب عادت‌های اتمی',sku:'BK-102',price:320000,next:328000,stock:8,status:'ready'},{id:3,name:'کتاب انسان در جستجوی معنا',sku:'BK-103',price:180000,next:180000,stock:0,status:'same'},{id:4,name:'کتاب کار عمیق',sku:'BK-104',price:280000,next:291000,stock:5,status:'ready'}];
const fa=n=>new Intl.NumberFormat('fa-IR').format(n);
const labels={review:'نیازمند بررسی',ready:'آماده به‌روزرسانی',same:'بدون تغییر',done:'اعمال آزمایشی'};
const nav=[['overview','نمای کلی',LayoutDashboard],['apu','قیمت و موجودی',RefreshCw],['channels','کانال‌های ارتباطی',MessagesSquare],['settings','تنظیمات',SlidersHorizontal]];
export default function Workspace({admin=false}){
 const params=useSearchParams();const requested=params.get('tab');
 const [tab,setTab]=useState(nav.some(n=>n[0]===requested)?requested:'overview');
 const [rows,setRows]=useState(initial);const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [menu,setMenu]=useState(false);const [notice,setNotice]=useState('');const [runs,setRuns]=useState([]);const [busy,setBusy]=useState(false);
 const [business,setBusiness]=useState('فروشگاه نمونه');const [limit,setLimit]=useState(5);const [auto,setAuto]=useState(false);const [title,setTitle]=useState('کارهای تکراری را به دلسا بسپار.');
 const [connected,setConnected]=useState([]);
 const selected=nav.find(n=>n[0]===tab);
 const filtered=rows.filter(r=>r.name.includes(query)||r.sku.toLowerCase().includes(query.toLowerCase())).filter(r=>filter==='all'||r.status===filter);
 function go(id){setTab(id);setMenu(false);setNotice('');}
 function simulate(){setBusy(true);setNotice('');setTimeout(()=>{const count=rows.filter(r=>r.status==='ready').length;setRows(prev=>prev.map(r=>r.status==='ready'?{...r,price:r.next,status:'done'}:r));setRuns(prev=>[{id:Date.now(),time:new Date().toLocaleTimeString('fa-IR'),count},...prev]);setNotice(count?`${fa(count)} محصول در همین پیش‌نمایش به‌روزرسانی شد؛ فروشگاه واقعی تغییر نکرد.`:'محصول آماده‌ای برای تغییر وجود ندارد. موارد نیازمند بررسی را تأیید کن.');setBusy(false);},700);}
 function csv(){const data='\uFEFF'+[['نام محصول','شناسه','قیمت فعلی','قیمت منبع','موجودی','وضعیت'],...rows.map(r=>[r.name,r.sku,r.price,r.next,r.stock,labels[r.status]])].map(r=>r.map(c=>'"'+String(c).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='delsa-demo-products.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="workspace"><aside className={'sidebar '+(menu?'open':'')}><div className="side-brand"><Link href="/" className="brand">delsa<span>●</span></Link><button className="icon mobile-only" onClick={()=>setMenu(false)} aria-label="بستن منو"><X/></button></div><div className="workspace-name"><span className="avatar">د</span><div><strong>{admin?'مدیریت دلسا':business}</strong><small>محیط نمایشی</small></div></div><span className="nav-caption">{admin?'پیش‌نمایش مدیریت':'فضای کار'}</span><nav>{nav.map(([id,name,Icon])=><button key={id} onClick={()=>go(id)} className={tab===id?'active':''}><Icon size={20}/>{admin&&id==='settings'?'محتوای سایت':name}</button>)}</nav><div className="side-bottom"><div className="trial"><CircleHelp size={20}/><strong>قبل از اتصال، تجربه کن.</strong><p>تمام داده‌های این محیط نمونه‌اند.</p></div><Link href={admin?'/dashboard':'/admin'}><Shield size={18}/>{admin?'داشبورد مشتری':'پیش‌نمایش پنل مدیریت'}</Link><Link href="/"><ArrowLeft size={18}/>بازگشت به سایت</Link></div></aside>{menu&&<button className="scrim" aria-label="بستن منو" onClick={()=>setMenu(false)}/>}
 <div className="workspace-body"><header className="workspace-header"><div><button className="icon mobile-only" onClick={()=>setMenu(true)} aria-label="باز کردن منو"><Menu/></button><span>فضای کار</span><span className="muted"> / </span><strong>{selected?.[1]}</strong></div><span className="badge">نسخه آزمایشی</span></header><main className="workspace-main"><div className="demo-banner"><span><strong>محیط آزمایشی</strong> · اتصال واقعی و ذخیره دائمی هنوز فعال نیست.</span><span>بدون تغییر در اطلاعات کسب‌وکار</span></div><div className="page-heading"><div><span className="eyebrow">{admin?'مدیریت دلسا':'داشبورد کسب‌وکار'}</span><h1>{tab==='overview'?'همه‌چیز، در یک نگاه.':admin&&tab==='settings'?'محتوای صفحه اصلی':selected?.[1]}</h1><p>{tab==='overview'?'وضعیت نمونه سرویس‌ها و کارهای نیازمند توجه را ببین.':tab==='apu'?'تغییرات نمونه قیمت و موجودی را بررسی کن.':tab==='channels'?'فضای اتصال پیام‌رسان‌های کسب‌وکارت.':'تغییرات این بخش فقط تا بازآوری صفحه باقی می‌ماند.'}</p></div>{(tab==='overview'||tab==='apu')&&<button className="button primary" onClick={simulate} disabled={busy}><RefreshCw size={18} className={busy?'spin':''}/>{busy?'در حال شبیه‌سازی…':'اجرای آزمایشی APU'}</button>}</div>
 {notice&&<div className="notice" role="status">{notice}<button className="icon" aria-label="بستن پیام" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {tab==='overview'&&<><div className="stats"><article><Package/><span>محصولات نمونه</span><strong>{fa(rows.length)}</strong><small>کاتالوگ آزمایشی</small></article><article><RefreshCw/><span>آماده به‌روزرسانی</span><strong>{fa(rows.filter(r=>r.status==='ready').length)}</strong><small>در انتظار اجرای نمونه</small></article><article><Clock/><span>نیازمند بررسی</span><strong>{fa(rows.filter(r=>r.status==='review').length)}</strong><small>تغییر قیمت بالاتر از حد نمونه</small></article><article><Link2/><span>اتصال واقعی</span><strong>۰</strong><small>نیازمند پیکربندی</small></article></div><div className="overview-grid"><section className="panel"><div className="panel-heading"><h2>قدم بعدی تو</h2><span className="tag">شروع کار</span></div><div className="next-step"><span className="step-icon"><Store/></span><div><h3>فروشگاهت را به دلسا وصل کن</h3><p>فعلاً جریان کار را با داده‌های نمونه بررسی کن. اتصال واقعی در مرحله راه‌اندازی انجام می‌شود.</p><button className="text-button" onClick={()=>go('apu')}>بررسی محصولات نمونه <ArrowLeft size={18}/></button></div></div><div className="setup-row"><Check size={19}/><span>محیط آزمایشی آماده است</span></div><div className="setup-row muted"><span className="number">۲</span><span>راه‌اندازی حساب و اتصال فروشگاه</span><span className="tag">مرحله بعد</span></div><div className="setup-row muted"><span className="number">۳</span><span>تعیین قواعد و شروع اجرای واقعی</span></div></section><section className="panel"><div className="panel-heading"><h2>گزارش اجرا</h2><Clock size={20}/></div>{runs.length===0?<div className="empty"><RefreshCw size={32}/><h3>هنوز اجرایی انجام نشده</h3><p>برای دیدن نتیجه، یک بار APU را به‌صورت آزمایشی اجرا کن.</p></div>:<div className="run-list">{runs.map(r=><article key={r.id}><Check size={18}/><div><strong>اجرای آزمایشی انجام شد</strong><p>{fa(r.count)} به‌روزرسانی نمونه · {r.time}</p></div></article>)}</div>}</section></div><section className="channel-strip"><div><MessagesSquare size={25}/><div><h3>ارتباط با مشتری، در کنار فروشگاه</h3><p>بله، ایتا، روبیکا و سروش در طرح نسخه اولیه</p></div></div><button className="button" onClick={()=>go('channels')}>مشاهده کانال‌ها <ArrowLeft size={18}/></button></section></>}
 {tab==='apu'&&<section className="panel"><div className="table-toolbar"><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جست‌وجوی نام یا شناسه محصول" aria-label="جست‌وجوی محصولات"/></label><select aria-label="فیلتر وضعیت" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">همه وضعیت‌ها</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button className="button small" onClick={csv}><Download size={17}/>خروجی CSV</button></div><div className="table-scroll"><table><thead><tr><th>محصول نمونه</th><th>قیمت فعلی / تومان</th><th>قیمت منبع / تومان</th><th>موجودی</th><th>وضعیت</th><th>اقدام</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small dir="ltr">{r.sku}</small></td><td>{fa(r.price)}</td><td>{fa(r.next)}</td><td>{fa(r.stock)}</td><td><span className={'status '+r.status}>{labels[r.status]}</span></td><td>{r.status==='review'?<button className="text-button" onClick={()=>{setRows(prev=>prev.map(x=>x.id===r.id?{...x,status:'ready'}:x));setNotice('محصول برای اجرای آزمایشی تأیید شد.');}}>تأیید تغییر</button>:<span className="muted">—</span>}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">محصولی با این شرایط پیدا نشد.</div>}</div><p className="table-note">همه قیمت‌ها و محصولات نمونه‌اند. خروجی CSV نیز همین اطلاعات نمونه را شامل می‌شود.</p></section>}
 {tab==='channels'&&<div className="channels-grid">{['بله','ایتا','روبیکا','سروش'].map((name,i)=><article className="panel channel-card" key={name}><div className="channel-letter">{name[0]}</div><h2>{name}</h2><span className="status same">{connected.includes(name)?'تنظیم نمونه ثبت شد':'متصل نیست'}</span><p>برای اتصال واقعی، سرویس {name} و دسترسی‌های حساب باید پیکربندی شوند.</p><button className="button" onClick={()=>{setConnected(prev=>prev.includes(name)?prev:prev.concat(name));setNotice(`برای ${name} وضعیت نمونه ثبت شد. هیچ اتصال واقعی برقرار نشده است.`);}} disabled={connected.includes(name)}>{connected.includes(name)?'در انتظار راه‌اندازی':'آزمایش انتخاب کانال'}<Link2 size={17}/></button></article>)}</div>}
 {tab==='settings'&&<form className="panel settings" onSubmit={e=>{e.preventDefault();setNotice('تغییرات نمونه در همین صفحه اعمال شد؛ ذخیره دائمی هنوز فعال نیست.');}}><h2>{admin?'ویرایش نمونه محتوا':'تنظیمات فضای کار'}</h2><label>نام کسب‌وکار<input required maxLength={60} value={business} onChange={e=>setBusiness(e.target.value)}/></label>{admin&&<><label>عنوان صفحه اصلی<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="content-preview"><span className="eyebrow">پیش‌نمایش عنوان</span><h2>{title}</h2><p>این تغییر در صفحه عمومی منتشر نمی‌شود.</p></div></>}<label>حد بررسی تغییر قیمت (درصد)<input type="number" min="1" max="100" value={limit} onChange={e=>setLimit(e.target.value)}/><small>تنظیم نمایشی؛ هنوز به موتور اجرای APU متصل نیست.</small></label><label className="checkbox"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>درخواست اجرای زمان‌بندی‌شده پس از راه‌اندازی</label><button className="button primary" type="submit">اعمال در پیش‌نمایش <Check size={18}/></button></form>}
 <footer className="workspace-footer"><span>دلسا · فرصت بیشتر برای کارهای مهم‌تر</span><span>پیش‌نمایش رابط کاربری</span></footer></main></div></div>
}
