import {notFound} from 'next/navigation';
import {createClient} from '../../../../lib/supabase/server';
import {normalizeDocument} from '../../../../lib/site-builder';
import BuilderStorefront from '../../../../components/BuilderStorefront';
import {defaultShop} from '../../../../lib/builder-commerce';
export const dynamic='force-dynamic';
async function read(params){const {slug,path=[]}=await params;if(!/^[a-z0-9][a-z0-9-]{2,47}$/.test(slug)||path.length>2)return null;const db=await createClient();const {data}=await db.from('builder_publications').select('site_id,name,slug,document').eq('slug',slug).eq('is_live',true).maybeSingle();if(!data)return null;const doc=normalizeDocument(data.document);let view='page',pageSlug=path[0]||'',productSlug='';if(['shop','cart','checkout','orders'].includes(path[0])&&path.length===1)view=path[0];else if(path[0]==='product'&&path.length===2){view='product';productSlug=path[1]}else if(path.length>1||!doc.pages.some(p=>p.slug===pageSlug))return null;const [catalog,settings]=await Promise.all([db.from('builder_products').select('*,variants:builder_variants(*)').eq('site_id',data.site_id).eq('status','published').order('created_at',{ascending:false}).limit(1000),db.from('builder_shop_settings').select('*').eq('site_id',data.site_id).maybeSingle()]);if(catalog.error||settings.error)throw new Error('Store data unavailable');const products=(catalog.data||[]).map(p=>({...p,variants:p.variants.filter(v=>v.enabled)}));if(view==='product'&&!products.some(p=>p.slug===productSlug))return null;return {site:{...data,document:doc},products,settings:{...defaultShop,...settings.data,free_shipping_threshold:settings.data?.free_shipping_threshold??null},view,pageSlug,productSlug}}
export async function generateMetadata({params}){const s=await read(params),product=s?.products.find(p=>p.slug===s.productSlug);return {title:product?product.title+' | '+s.site.name:s?.site.name||'سایت یافت نشد',description:product?.summary||s?.site.document.description||undefined,robots:{index:Boolean(s)&&!['cart','checkout','orders'].includes(s.view),follow:Boolean(s)},referrer:'same-origin'}}
export default async function PublicSite({params}){const s=await read(params);if(!s)notFound();return <BuilderStorefront key={s.site.slug} {...s}/>}
